package com.addlove.service.goods.model;

/**
 * 品牌表
 * @author lw
 *
 */
public class BasBrandModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.BRANDCODE
     * 品牌编码
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String brandCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.BRANDNAME
     * 品牌名称
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.BRANDENAME
     * 品牌英文名称
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String brandEName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.REMARK
     * 说明
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.BRANDMN
     * 品牌助记符
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String brandMn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.UDP1
     *
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String udp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.UDP2
     *
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String udp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.UDP3
     *
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String udp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.UDP4
     *
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String udp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.UDP5
     *
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String udp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBASBRAND.UDP6
     *
     * @mbggenerated Tue Jul 09 11:58:58 CST 2019
     */
    private String udp6;

    /**
     * @return the brandCode
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * @param brandCode the brandCode to set
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode;
    }

    /**
     * @return the brandName
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * @param brandName the brandName to set
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * @return the brandEName
     */
    public String getBrandEName() {
        return brandEName;
    }

    /**
     * @param brandEName the brandEName to set
     */
    public void setBrandEName(String brandEName) {
        this.brandEName = brandEName;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the brandMn
     */
    public String getBrandMn() {
        return brandMn;
    }

    /**
     * @param brandMn the brandMn to set
     */
    public void setBrandMn(String brandMn) {
        this.brandMn = brandMn;
    }

    /**
     * @return the udp1
     */
    public String getUdp1() {
        return udp1;
    }

    /**
     * @param udp1 the udp1 to set
     */
    public void setUdp1(String udp1) {
        this.udp1 = udp1;
    }

    /**
     * @return the udp2
     */
    public String getUdp2() {
        return udp2;
    }

    /**
     * @param udp2 the udp2 to set
     */
    public void setUdp2(String udp2) {
        this.udp2 = udp2;
    }

    /**
     * @return the udp3
     */
    public String getUdp3() {
        return udp3;
    }

    /**
     * @param udp3 the udp3 to set
     */
    public void setUdp3(String udp3) {
        this.udp3 = udp3;
    }

    /**
     * @return the udp4
     */
    public String getUdp4() {
        return udp4;
    }

    /**
     * @param udp4 the udp4 to set
     */
    public void setUdp4(String udp4) {
        this.udp4 = udp4;
    }

    /**
     * @return the udp5
     */
    public String getUdp5() {
        return udp5;
    }

    /**
     * @param udp5 the udp5 to set
     */
    public void setUdp5(String udp5) {
        this.udp5 = udp5;
    }

    /**
     * @return the udp6
     */
    public String getUdp6() {
        return udp6;
    }

    /**
     * @param udp6 the udp6 to set
     */
    public void setUdp6(String udp6) {
        this.udp6 = udp6;
    }
}