package com.addlove.service.goods.model;

/**
 * 报损申请单明细表
 * @author lw
 *
 */
public class CouBsApplyBodyModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.BILLNO
     * 单据号
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.SERIALNO
     * 序号
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long serialNo;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPID
     * 部门ID
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPCODE
     * 部门编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPNAME
     * 部门名称
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUID
     * 商品Id
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long pluId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUCODE
     * 商品编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String pluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUNAME
     * 商品名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String pluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.EXPLUCODE
     * 特征码编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String exPluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.EXPLUNAME
     * 特征码名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String exPluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.BARCODE
     * 商品条码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDBODY.UNIT
     *
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDBODY.SPEC
     *
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUBSAPPLYHEAD.BSCOUNT
     * 报损数量
     * @mbggenerated Wed Aug 14 11:43:57 CST 2019
     */
    private Double bsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUBSAPPLYBODY.KWCODE
     * 库位编码
     * @mbggenerated Wed Aug 14 11:43:57 CST 2019
     */
    private String kwCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUBSAPPLYBODY.CARGONO
     * 货号
     * @mbggenerated Wed Aug 14 11:43:57 CST 2019
     */
    private String carGoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUBSAPPLYBODY.YKREASON
     * 报损原因
     * @mbggenerated Wed Aug 14 11:43:57 CST 2019
     */
    private String ykReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUBSAPPLYBODY.REMARK
     *
     * @mbggenerated Wed Aug 14 11:43:57 CST 2019
     */
    private String remark;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * @return the serialNo
     */
    public Long getSerialNo() {
        return serialNo;
    }

    /**
     * @param serialNo the serialNo to set
     */
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * @return the depId
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * @param depId the depId to set
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * @return the depName
     */
    public String getDepName() {
        return depName;
    }

    /**
     * @param depName the depName to set
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * @return the pluId
     */
    public Long getPluId() {
        return pluId;
    }

    /**
     * @param pluId the pluId to set
     */
    public void setPluId(Long pluId) {
        this.pluId = pluId;
    }

    /**
     * @return the pluCode
     */
    public String getPluCode() {
        return pluCode;
    }

    /**
     * @param pluCode the pluCode to set
     */
    public void setPluCode(String pluCode) {
        this.pluCode = pluCode;
    }

    /**
     * @return the pluName
     */
    public String getPluName() {
        return pluName;
    }

    /**
     * @param pluName the pluName to set
     */
    public void setPluName(String pluName) {
        this.pluName = pluName;
    }

    /**
     * @return the exPluCode
     */
    public String getExPluCode() {
        return exPluCode;
    }

    /**
     * @param exPluCode the exPluCode to set
     */
    public void setExPluCode(String exPluCode) {
        this.exPluCode = exPluCode;
    }

    /**
     * @return the exPluName
     */
    public String getExPluName() {
        return exPluName;
    }

    /**
     * @param exPluName the exPluName to set
     */
    public void setExPluName(String exPluName) {
        this.exPluName = exPluName;
    }

    /**
     * @return the barCode
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * @param barCode the barCode to set
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    /**
     * @return the unit
     */
    public String getUnit() {
        return unit;
    }

    /**
     * @param unit the unit to set
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * @return the spec
     */
    public String getSpec() {
        return spec;
    }

    /**
     * @param spec the spec to set
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * @return the bsCount
     */
    public Double getBsCount() {
        return bsCount;
    }

    /**
     * @param bsCount the bsCount to set
     */
    public void setBsCount(Double bsCount) {
        this.bsCount = bsCount;
    }

    /**
     * @return the kwCode
     */
    public String getKwCode() {
        return kwCode;
    }

    /**
     * @param kwCode the kwCode to set
     */
    public void setKwCode(String kwCode) {
        this.kwCode = kwCode;
    }

    /**
     * @return the carGoNo
     */
    public String getCarGoNo() {
        return carGoNo;
    }

    /**
     * @param carGoNo the carGoNo to set
     */
    public void setCarGoNo(String carGoNo) {
        this.carGoNo = carGoNo;
    }

    /**
     * @return the ykReason
     */
    public String getYkReason() {
        return ykReason;
    }

    /**
     * @param ykReason the ykReason to set
     */
    public void setYkReason(String ykReason) {
        this.ykReason = ykReason;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}