package com.addlove.service.goods.model;

/**
 * 门店盘点单主表
 * @author lw
 *
 */
public class CouMdPdHeadModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.BILLNO
     * 单据号
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.LRDATE
     * 录入日期
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String lrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.USERID
     * 录入人ID
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.USERCODE
     * 录入人编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.USERNAME
     * 录入人姓名
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.JZDATE
     * 记账日期
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String jzDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.JZRID
     * 记账人ID
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long jzrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.JZRCODE
     * 记账人编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String jzrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.JZRNAME
     * 记账人姓名
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String jzrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.RPTDATE
     * 报表日期
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String rptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.PRNTIMES
     * 打印次数
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long prnTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.PRNDATE
     * 打印时间
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String prnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.TIMEMARK
     * 时间戳
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long timeMark;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.ORGCODE
     * 组织编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.ORGNAME
     * 组织名称
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.INORGCODE
     * 内部组织编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String inOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPID
     * 部门ID
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPCODE
     * 部门编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPNAME
     * 部门名称
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.CKCODE
     * 仓库编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String ckCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.CKNAME
     * 仓库名称
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String ckName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.PDSTARTDATE
     * 执行日期
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String pdStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.YWTYPE
     * 业务类型
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String ywType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.BILLTYPE
     * 单据类型:0-日盘；1-周盘；2-月盘；
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.COUSTATUS
     * 盘点状态:0-未执行；1-已执行；2-已完成；
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String couStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.ZMCOUNT
     * 账面数量
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double zmCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.ZMHCOST
     * 账面含税进价金额
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double zmHCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.ZMWCOST
     * 账面无税进价金额
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double zmWCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.ZMSCOST
     * 账面售价金额
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double zmSCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.SJCOUNT
     * 实盘数量
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double sJCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.SJHCOST
     * 实盘含税进价金额
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double sJhCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.SJWCOST
     * 实盘无税进价金额
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double sJwCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.SJSCOST
     * 实盘售价金额
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double sJsCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.YKCOUNT
     * 盈亏数量
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double ykCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.YKHCOST
     * 盈亏含税进价金额
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double ykHCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.YKWCOST
     * 盈亏无税进价金额
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double ykWCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.YKSCOST
     * 盈亏售价金额
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Double ykSCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.DATASTATUS
     * 数据状态:0－录入；1－审批；2－转审；3－提交；4-可记账；9-关闭
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.REMARK
     * 备注
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String remark;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * @return the lrDate
     */
    public String getLrDate() {
        return lrDate;
    }

    /**
     * @param lrDate the lrDate to set
     */
    public void setLrDate(String lrDate) {
        this.lrDate = lrDate;
    }

    /**
     * @return the userId
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId the userId to set
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return the userCode
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * @param userCode the userCode to set
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return the jzDate
     */
    public String getJzDate() {
        return jzDate;
    }

    /**
     * @param jzDate the jzDate to set
     */
    public void setJzDate(String jzDate) {
        this.jzDate = jzDate;
    }

    /**
     * @return the jzrId
     */
    public Long getJzrId() {
        return jzrId;
    }

    /**
     * @param jzrId the jzrId to set
     */
    public void setJzrId(Long jzrId) {
        this.jzrId = jzrId;
    }

    /**
     * @return the jzrCode
     */
    public String getJzrCode() {
        return jzrCode;
    }

    /**
     * @param jzrCode the jzrCode to set
     */
    public void setJzrCode(String jzrCode) {
        this.jzrCode = jzrCode;
    }

    /**
     * @return the jzrName
     */
    public String getJzrName() {
        return jzrName;
    }

    /**
     * @param jzrName the jzrName to set
     */
    public void setJzrName(String jzrName) {
        this.jzrName = jzrName;
    }

    /**
     * @return the rptDate
     */
    public String getRptDate() {
        return rptDate;
    }

    /**
     * @param rptDate the rptDate to set
     */
    public void setRptDate(String rptDate) {
        this.rptDate = rptDate;
    }

    /**
     * @return the prnTimes
     */
    public Long getPrnTimes() {
        return prnTimes;
    }

    /**
     * @param prnTimes the prnTimes to set
     */
    public void setPrnTimes(Long prnTimes) {
        this.prnTimes = prnTimes;
    }

    /**
     * @return the prnDate
     */
    public String getPrnDate() {
        return prnDate;
    }

    /**
     * @param prnDate the prnDate to set
     */
    public void setPrnDate(String prnDate) {
        this.prnDate = prnDate;
    }

    /**
     * @return the timeMark
     */
    public Long getTimeMark() {
        return timeMark;
    }

    /**
     * @param timeMark the timeMark to set
     */
    public void setTimeMark(Long timeMark) {
        this.timeMark = timeMark;
    }

    /**
     * @return the orgCode
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * @param orgCode the orgCode to set
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * @return the orgName
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * @param orgName the orgName to set
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * @return the inOrgCode
     */
    public String getInOrgCode() {
        return inOrgCode;
    }

    /**
     * @param inOrgCode the inOrgCode to set
     */
    public void setInOrgCode(String inOrgCode) {
        this.inOrgCode = inOrgCode;
    }

    /**
     * @return the depId
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * @param depId the depId to set
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * @return the depName
     */
    public String getDepName() {
        return depName;
    }

    /**
     * @param depName the depName to set
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * @return the ckCode
     */
    public String getCkCode() {
        return ckCode;
    }

    /**
     * @param ckCode the ckCode to set
     */
    public void setCkCode(String ckCode) {
        this.ckCode = ckCode;
    }

    /**
     * @return the ckName
     */
    public String getCkName() {
        return ckName;
    }

    /**
     * @param ckName the ckName to set
     */
    public void setCkName(String ckName) {
        this.ckName = ckName;
    }

    /**
     * @return the pdStartDate
     */
    public String getPdStartDate() {
        return pdStartDate;
    }

    /**
     * @param pdStartDate the pdStartDate to set
     */
    public void setPdStartDate(String pdStartDate) {
        this.pdStartDate = pdStartDate;
    }

    /**
     * @return the ywType
     */
    public String getYwType() {
        return ywType;
    }

    /**
     * @param ywType the ywType to set
     */
    public void setYwType(String ywType) {
        this.ywType = ywType;
    }

    /**
     * @return the billType
     */
    public String getBillType() {
        return billType;
    }

    /**
     * @param billType the billType to set
     */
    public void setBillType(String billType) {
        this.billType = billType;
    }

    /**
     * @return the couStatus
     */
    public String getCouStatus() {
        return couStatus;
    }

    /**
     * @param couStatus the couStatus to set
     */
    public void setCouStatus(String couStatus) {
        this.couStatus = couStatus;
    }

    /**
     * @return the zmCount
     */
    public Double getZmCount() {
        return zmCount;
    }

    /**
     * @param zmCount the zmCount to set
     */
    public void setZmCount(Double zmCount) {
        this.zmCount = zmCount;
    }

    /**
     * @return the zmHCost
     */
    public Double getZmHCost() {
        return zmHCost;
    }

    /**
     * @param zmHCost the zmHCost to set
     */
    public void setZmHCost(Double zmHCost) {
        this.zmHCost = zmHCost;
    }

    /**
     * @return the zmWCost
     */
    public Double getZmWCost() {
        return zmWCost;
    }

    /**
     * @param zmWCost the zmWCost to set
     */
    public void setZmWCost(Double zmWCost) {
        this.zmWCost = zmWCost;
    }

    /**
     * @return the zmSCost
     */
    public Double getZmSCost() {
        return zmSCost;
    }

    /**
     * @param zmSCost the zmSCost to set
     */
    public void setZmSCost(Double zmSCost) {
        this.zmSCost = zmSCost;
    }

    /**
     * @return the sJCount
     */
    public Double getsJCount() {
        return sJCount;
    }

    /**
     * @param sJCount the sJCount to set
     */
    public void setsJCount(Double sJCount) {
        this.sJCount = sJCount;
    }

    /**
     * @return the sJhCost
     */
    public Double getsJhCost() {
        return sJhCost;
    }

    /**
     * @param sJhCost the sJhCost to set
     */
    public void setsJhCost(Double sJhCost) {
        this.sJhCost = sJhCost;
    }

    /**
     * @return the sJwCost
     */
    public Double getsJwCost() {
        return sJwCost;
    }

    /**
     * @param sJwCost the sJwCost to set
     */
    public void setsJwCost(Double sJwCost) {
        this.sJwCost = sJwCost;
    }

    /**
     * @return the sJsCost
     */
    public Double getsJsCost() {
        return sJsCost;
    }

    /**
     * @param sJsCost the sJsCost to set
     */
    public void setsJsCost(Double sJsCost) {
        this.sJsCost = sJsCost;
    }

    /**
     * @return the ykCount
     */
    public Double getYkCount() {
        return ykCount;
    }

    /**
     * @param ykCount the ykCount to set
     */
    public void setYkCount(Double ykCount) {
        this.ykCount = ykCount;
    }

    /**
     * @return the ykHCost
     */
    public Double getYkHCost() {
        return ykHCost;
    }

    /**
     * @param ykHCost the ykHCost to set
     */
    public void setYkHCost(Double ykHCost) {
        this.ykHCost = ykHCost;
    }

    /**
     * @return the ykWCost
     */
    public Double getYkWCost() {
        return ykWCost;
    }

    /**
     * @param ykWCost the ykWCost to set
     */
    public void setYkWCost(Double ykWCost) {
        this.ykWCost = ykWCost;
    }

    /**
     * @return the ykSCost
     */
    public Double getYkSCost() {
        return ykSCost;
    }

    /**
     * @param ykSCost the ykSCost to set
     */
    public void setYkSCost(Double ykSCost) {
        this.ykSCost = ykSCost;
    }

    /**
     * @return the dataStatus
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * @param dataStatus the dataStatus to set
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}