package com.addlove.service.goods.model;

/**
 * 门店要货单主表
 * @author lw
 *
 */
public class OrdAdlYhHeadModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.BILLNO
     * 单据号
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.LRDATE
     * 录入日期
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String lrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.USERID
     * 录入人ID
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.USERCODE
     * 录入人编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.USERNAME
     * 录入人姓名
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.JZDATE
     * 记账日期
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String jzDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.JZRID
     * 记账人ID
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long jzrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.JZRCODE
     * 记账人编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String jzrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.JZRNAME
     * 记账人姓名
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String jzrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.JZTYPE
     * 记账类型:0-手工1-系统
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String jzType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.RPTDATE
     * 报表日期
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String rptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.PRNTIMES
     * 打印次数
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long prnTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.PRNDATE
     * 打印时间
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String prnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.TIMEMARK
     * 时间戳
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long timeMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.YWTYPE
     * 业务类型:6205
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String ywType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.YWIOTYPE
     * 内外部业务类型:0-内部业务；1-外部业务
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String ywIoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.ORGCODE
     * 组织编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.ORGNAME
     * 组织名称
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPID
     * 部门ID
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPCODE
     * 部门编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPNAME
     * 部门名称
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.ISURGENT
     * 紧急要货：0-否；1-是
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String isUrgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ZBORGCODE
     * 供应商编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String zbOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ZBORGNAME
     * 供应商名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String zbOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.SDDATE
     * 要货送达日期
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String sdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.SHADDR
     * 收货地址
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String shAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.YHCOUNT
     * 要货数量
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private Double yhCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.YWSTATUS
     * 要货状态:0-未确认1-已确认；2-已作废；要货确认时更改为已确认，后台结账时根据期限进行作废，后者手工作废
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String ywStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TCOUMDPDHEAD.DATASTATUS
     * 数据状态:0－录入；1－审批；2－转审；3－提交；4-可记账；9-关闭
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.YHTOTAL
     * 要货金额
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private Double yhTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.REMARK
     * 备注
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.MODELCODE
     * 模板编码
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String modelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDCDADLYHHEAD.YHBC
     * 要货波次
     * @mbggenerated Mon Aug 19 13:44:21 CST 2019
     */
    private String yhBc;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * @return the lrDate
     */
    public String getLrDate() {
        return lrDate;
    }

    /**
     * @param lrDate the lrDate to set
     */
    public void setLrDate(String lrDate) {
        this.lrDate = lrDate;
    }

    /**
     * @return the userId
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId the userId to set
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return the userCode
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * @param userCode the userCode to set
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return the jzDate
     */
    public String getJzDate() {
        return jzDate;
    }

    /**
     * @param jzDate the jzDate to set
     */
    public void setJzDate(String jzDate) {
        this.jzDate = jzDate;
    }

    /**
     * @return the jzrId
     */
    public Long getJzrId() {
        return jzrId;
    }

    /**
     * @param jzrId the jzrId to set
     */
    public void setJzrId(Long jzrId) {
        this.jzrId = jzrId;
    }

    /**
     * @return the jzrCode
     */
    public String getJzrCode() {
        return jzrCode;
    }

    /**
     * @param jzrCode the jzrCode to set
     */
    public void setJzrCode(String jzrCode) {
        this.jzrCode = jzrCode;
    }

    /**
     * @return the jzrName
     */
    public String getJzrName() {
        return jzrName;
    }

    /**
     * @param jzrName the jzrName to set
     */
    public void setJzrName(String jzrName) {
        this.jzrName = jzrName;
    }

    /**
     * @return the jzType
     */
    public String getJzType() {
        return jzType;
    }

    /**
     * @param jzType the jzType to set
     */
    public void setJzType(String jzType) {
        this.jzType = jzType;
    }

    /**
     * @return the rptDate
     */
    public String getRptDate() {
        return rptDate;
    }

    /**
     * @param rptDate the rptDate to set
     */
    public void setRptDate(String rptDate) {
        this.rptDate = rptDate;
    }

    /**
     * @return the prnTimes
     */
    public Long getPrnTimes() {
        return prnTimes;
    }

    /**
     * @param prnTimes the prnTimes to set
     */
    public void setPrnTimes(Long prnTimes) {
        this.prnTimes = prnTimes;
    }

    /**
     * @return the prnDate
     */
    public String getPrnDate() {
        return prnDate;
    }

    /**
     * @param prnDate the prnDate to set
     */
    public void setPrnDate(String prnDate) {
        this.prnDate = prnDate;
    }

    /**
     * @return the timeMark
     */
    public Long getTimeMark() {
        return timeMark;
    }

    /**
     * @param timeMark the timeMark to set
     */
    public void setTimeMark(Long timeMark) {
        this.timeMark = timeMark;
    }

    /**
     * @return the ywType
     */
    public String getYwType() {
        return ywType;
    }

    /**
     * @param ywType the ywType to set
     */
    public void setYwType(String ywType) {
        this.ywType = ywType;
    }

    /**
     * @return the ywIoType
     */
    public String getYwIoType() {
        return ywIoType;
    }

    /**
     * @param ywIoType the ywIoType to set
     */
    public void setYwIoType(String ywIoType) {
        this.ywIoType = ywIoType;
    }

    /**
     * @return the orgCode
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * @param orgCode the orgCode to set
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * @return the orgName
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * @param orgName the orgName to set
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * @return the depId
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * @param depId the depId to set
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * @return the depName
     */
    public String getDepName() {
        return depName;
    }

    /**
     * @param depName the depName to set
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * @return the isUrgent
     */
    public String getIsUrgent() {
        return isUrgent;
    }

    /**
     * @param isUrgent the isUrgent to set
     */
    public void setIsUrgent(String isUrgent) {
        this.isUrgent = isUrgent;
    }

    /**
     * @return the zbOrgCode
     */
    public String getZbOrgCode() {
        return zbOrgCode;
    }

    /**
     * @param zbOrgCode the zbOrgCode to set
     */
    public void setZbOrgCode(String zbOrgCode) {
        this.zbOrgCode = zbOrgCode;
    }

    /**
     * @return the zbOrgName
     */
    public String getZbOrgName() {
        return zbOrgName;
    }

    /**
     * @param zbOrgName the zbOrgName to set
     */
    public void setZbOrgName(String zbOrgName) {
        this.zbOrgName = zbOrgName;
    }

    /**
     * @return the sdDate
     */
    public String getSdDate() {
        return sdDate;
    }

    /**
     * @param sdDate the sdDate to set
     */
    public void setSdDate(String sdDate) {
        this.sdDate = sdDate;
    }

    /**
     * @return the shAddr
     */
    public String getShAddr() {
        return shAddr;
    }

    /**
     * @param shAddr the shAddr to set
     */
    public void setShAddr(String shAddr) {
        this.shAddr = shAddr;
    }

    /**
     * @return the yhCount
     */
    public Double getYhCount() {
        return yhCount;
    }

    /**
     * @param yhCount the yhCount to set
     */
    public void setYhCount(Double yhCount) {
        this.yhCount = yhCount;
    }

    /**
     * @return the ywStatus
     */
    public String getYwStatus() {
        return ywStatus;
    }

    /**
     * @param ywStatus the ywStatus to set
     */
    public void setYwStatus(String ywStatus) {
        this.ywStatus = ywStatus;
    }

    /**
     * @return the dataStatus
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * @param dataStatus the dataStatus to set
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * @return the yhTotal
     */
    public Double getYhTotal() {
        return yhTotal;
    }

    /**
     * @param yhTotal the yhTotal to set
     */
    public void setYhTotal(Double yhTotal) {
        this.yhTotal = yhTotal;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the modelCode
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * @param modelCode the modelCode to set
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode;
    }

    /**
     * @return the yhBc
     */
    public String getYhBc() {
        return yhBc;
    }

    /**
     * @param yhBc the yhBc to set
     */
    public void setYhBc(String yhBc) {
        this.yhBc = yhBc;
    }
}