package com.addlove.service.goods.model;
/**
 * 验收单主表
 * @author lw
 *
 */
public class OrdJhHeadModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.BILLNO
     * 单据号
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.LRDATE
     * 录入日期
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String lrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.USERID
     * 录入人ID
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.USERCODE
     * 录入人编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.USERNAME
     * 录入人姓名
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ISNEEDTJWL
     * 是否需要提交:连锁制作的验收单，该值为'0',物流制作的验收单，该值为'1'。默认为0
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String isNeedTjwl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.TJDATE
     * 提交日期
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String tjDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.TJRID
     * 提交人ID
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long tjrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.TJRCODE
     * 提交人编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String tjrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.TJRNAME
     * 提交人姓名
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String tjrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.JZDATE
     * 记账日期
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String jzDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.JZRID
     * 记账人ID
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long jzrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.JZRCODE
     * 记账人编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String jzrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.JZRNAME
     * 记账人姓名
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String jzrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.JZTYPE
     * 记账类型：0-手工 1-系统。默认为0
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String jzType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.RPTDATE
     * 报表日期 
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String rptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.PRNTIMES
     * 打印次数
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Integer prnTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.PRNDATE
     * 打印时间
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String prnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.TIMEMARK
     * 时间戳
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long timeMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.YWTYPE
     * 业务类型：0904-物流采购验收 0905-门店采购验收 0906-无采购验收 0907-直送验收 0908-配送验收
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String ywType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.YWIOTYPE
     * 内外部业务类型
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String ywIoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.YSPLUTYPE
     * 是否赠品验收
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String ysPluType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ORGCODE
     * 组织编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ORGNAME
     * 组织名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.INORGCODE
     * 内部组织编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String inOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.HORGCODE
     * 货主组织编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String hOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.HORGNAME
     * 货主组织名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String hOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.DEPID
     * 部门Id
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.DEPCODE
     * 部门编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.DEPNAME
     * 部门名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ZBORGCODE
     * 总部组织编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String zbOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ZBORGNAME
     * 总部组织名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String zbOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SUPCODE
     * 供应商编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String supCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SUPNAME
     * 供应商名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String supName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.CNTID
     * 合同ID
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long cntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.HTCODE
     * 合同编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String htCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.HTNAME
     * 合同名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String htName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.JYMODE
     * 经营方式：0-经销；1-代销；2-联销
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String jyMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.JSCODE
     * 结算方式编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String jsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.PSCNTID
     * 配送合同ID
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long psCntid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.PSHTCODE
     * 配送合同号
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String psHtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.PSHTNAME
     * 配送合同名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String psHtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.PSJYMODE
     * 配送经营方式
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String psJyMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.PSJSCODE
     * 配送结算方式
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String psJsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.CKCODE
     * 仓库编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String ckCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.CKNAME
     * 仓库名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String ckName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.JHCOUNT
     * 进货数量
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long jhCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.HCOST
     * 含税进价金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long hCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.WCOST
     * 无税进价金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long wCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.JTAXTOTAL
     * 税额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long jtaxTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.PSCOST
     * 配送金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long psCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.STOTAL
     * 售价金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long sTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.CJTOTAL
     * 进销差价
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long cjTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.REFBILLTYPE
     * 相关单据类型：0902-采购；2003-配送
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String refBillType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.REFBILLNO
     * 相关单据号
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String refBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.YSRID
     * 验收人Id
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long ysRid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.YSRCODE
     * 验收人编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String ysrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.YSRNAME
     * 验收人姓名
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String ysrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ISFP
     * 是否开具发票：0-否；1-是 应实施人员要求隐藏
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String isFp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.REMARK
     * 备注
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.DATASTATUS
     * 数据状态：0－录入；1－审批；2－转审；3－提交；4-可记账；9-关闭
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ISYKYS
     * 是否越库验收:0-否；1-是；物流采购验收时才有效
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String isYkYs;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.TAG
     * 是否已收货:0-未验收；1-正常验收；2-异常验收(有差异验收)
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.TELEPHONE
     * 电话
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String telePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.FAX
     * 传真
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.LINKMAN
     * 联系人
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String linkMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.LKMTEL
     * 联系人电话
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String lkmTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.WPSCOST
     * 无税配送金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long wPsCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.XTAXTOTAL
     * 销项税额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long xtaxTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ORIGINTYPE
     * 来源类型:0-CMP录入；1-普通Pos录入；2-WebPos录入
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String originType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.PICKDATE
     * 送货确认日期
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String pickDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.FBBILLNO
     * 
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String fbBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.FBSTATUS
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String fbStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SHETPCODE
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String shetpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SHETPNAME
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String shetpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.CURRCODE
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String currCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ISSTDCURR
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String isStdCurr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.EXCHANGERATE
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long exchangErate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.STLCURRPSCOST
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long stlCurrPsCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SHRID
     * 送货人ID
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long shrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SHRCODE
     * 送货人
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String shrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SHRNAME
     * 送货人姓名
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String shrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SHRDATE
     * 送货确认日期
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String shrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.REVIEWMAN
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String reviewMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.MDBILLNO
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String mdBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.QRDATE
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String qrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.QRTYPE
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String qrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.QRRID
     * 
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long qrrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.QRRCODE
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String qrrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.QRRNAME
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String qrrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.ZBTHCKCODE
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String zbThckCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.REMARK2
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SCMQRDATE
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String scmqrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SCMQRTIME
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String scmqrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHHEAD.SCMQROPINION
     *
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String scmqrOpinion;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * @return the lrDate
     */
    public String getLrDate() {
        return lrDate;
    }

    /**
     * @param lrDate the lrDate to set
     */
    public void setLrDate(String lrDate) {
        this.lrDate = lrDate;
    }

    /**
     * @return the userId
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId the userId to set
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return the userCode
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * @param userCode the userCode to set
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return the isNeedTjwl
     */
    public String getIsNeedTjwl() {
        return isNeedTjwl;
    }

    /**
     * @param isNeedTjwl the isNeedTjwl to set
     */
    public void setIsNeedTjwl(String isNeedTjwl) {
        this.isNeedTjwl = isNeedTjwl;
    }

    /**
     * @return the tjDate
     */
    public String getTjDate() {
        return tjDate;
    }

    /**
     * @param tjDate the tjDate to set
     */
    public void setTjDate(String tjDate) {
        this.tjDate = tjDate;
    }

    /**
     * @return the tjrId
     */
    public Long getTjrId() {
        return tjrId;
    }

    /**
     * @param tjrId the tjrId to set
     */
    public void setTjrId(Long tjrId) {
        this.tjrId = tjrId;
    }

    /**
     * @return the tjrCode
     */
    public String getTjrCode() {
        return tjrCode;
    }

    /**
     * @param tjrCode the tjrCode to set
     */
    public void setTjrCode(String tjrCode) {
        this.tjrCode = tjrCode;
    }

    /**
     * @return the tjrName
     */
    public String getTjrName() {
        return tjrName;
    }

    /**
     * @param tjrName the tjrName to set
     */
    public void setTjrName(String tjrName) {
        this.tjrName = tjrName;
    }

    /**
     * @return the jzDate
     */
    public String getJzDate() {
        return jzDate;
    }

    /**
     * @param jzDate the jzDate to set
     */
    public void setJzDate(String jzDate) {
        this.jzDate = jzDate;
    }

    /**
     * @return the jzrId
     */
    public Long getJzrId() {
        return jzrId;
    }

    /**
     * @param jzrId the jzrId to set
     */
    public void setJzrId(Long jzrId) {
        this.jzrId = jzrId;
    }

    /**
     * @return the jzrCode
     */
    public String getJzrCode() {
        return jzrCode;
    }

    /**
     * @param jzrCode the jzrCode to set
     */
    public void setJzrCode(String jzrCode) {
        this.jzrCode = jzrCode;
    }

    /**
     * @return the jzrName
     */
    public String getJzrName() {
        return jzrName;
    }

    /**
     * @param jzrName the jzrName to set
     */
    public void setJzrName(String jzrName) {
        this.jzrName = jzrName;
    }

    /**
     * @return the jzType
     */
    public String getJzType() {
        return jzType;
    }

    /**
     * @param jzType the jzType to set
     */
    public void setJzType(String jzType) {
        this.jzType = jzType;
    }

    /**
     * @return the rptDate
     */
    public String getRptDate() {
        return rptDate;
    }

    /**
     * @param rptDate the rptDate to set
     */
    public void setRptDate(String rptDate) {
        this.rptDate = rptDate;
    }

    /**
     * @return the prnTimes
     */
    public Integer getPrnTimes() {
        return prnTimes;
    }

    /**
     * @param prnTimes the prnTimes to set
     */
    public void setPrnTimes(Integer prnTimes) {
        this.prnTimes = prnTimes;
    }

    /**
     * @return the prnDate
     */
    public String getPrnDate() {
        return prnDate;
    }

    /**
     * @param prnDate the prnDate to set
     */
    public void setPrnDate(String prnDate) {
        this.prnDate = prnDate;
    }

    /**
     * @return the timeMark
     */
    public Long getTimeMark() {
        return timeMark;
    }

    /**
     * @param timeMark the timeMark to set
     */
    public void setTimeMark(Long timeMark) {
        this.timeMark = timeMark;
    }

    /**
     * @return the ywType
     */
    public String getYwType() {
        return ywType;
    }

    /**
     * @param ywType the ywType to set
     */
    public void setYwType(String ywType) {
        this.ywType = ywType;
    }

    /**
     * @return the ywIoType
     */
    public String getYwIoType() {
        return ywIoType;
    }

    /**
     * @param ywIoType the ywIoType to set
     */
    public void setYwIoType(String ywIoType) {
        this.ywIoType = ywIoType;
    }

    /**
     * @return the ysPluType
     */
    public String getYsPluType() {
        return ysPluType;
    }

    /**
     * @param ysPluType the ysPluType to set
     */
    public void setYsPluType(String ysPluType) {
        this.ysPluType = ysPluType;
    }

    /**
     * @return the orgCode
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * @param orgCode the orgCode to set
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * @return the orgName
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * @param orgName the orgName to set
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * @return the inOrgCode
     */
    public String getInOrgCode() {
        return inOrgCode;
    }

    /**
     * @param inOrgCode the inOrgCode to set
     */
    public void setInOrgCode(String inOrgCode) {
        this.inOrgCode = inOrgCode;
    }

    /**
     * @return the hOrgCode
     */
    public String gethOrgCode() {
        return hOrgCode;
    }

    /**
     * @param hOrgCode the hOrgCode to set
     */
    public void sethOrgCode(String hOrgCode) {
        this.hOrgCode = hOrgCode;
    }

    /**
     * @return the hOrgName
     */
    public String gethOrgName() {
        return hOrgName;
    }

    /**
     * @param hOrgName the hOrgName to set
     */
    public void sethOrgName(String hOrgName) {
        this.hOrgName = hOrgName;
    }

    /**
     * @return the depId
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * @param depId the depId to set
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * @return the depName
     */
    public String getDepName() {
        return depName;
    }

    /**
     * @param depName the depName to set
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * @return the zbOrgCode
     */
    public String getZbOrgCode() {
        return zbOrgCode;
    }

    /**
     * @param zbOrgCode the zbOrgCode to set
     */
    public void setZbOrgCode(String zbOrgCode) {
        this.zbOrgCode = zbOrgCode;
    }

    /**
     * @return the zbOrgName
     */
    public String getZbOrgName() {
        return zbOrgName;
    }

    /**
     * @param zbOrgName the zbOrgName to set
     */
    public void setZbOrgName(String zbOrgName) {
        this.zbOrgName = zbOrgName;
    }

    /**
     * @return the supCode
     */
    public String getSupCode() {
        return supCode;
    }

    /**
     * @param supCode the supCode to set
     */
    public void setSupCode(String supCode) {
        this.supCode = supCode;
    }

    /**
     * @return the supName
     */
    public String getSupName() {
        return supName;
    }

    /**
     * @param supName the supName to set
     */
    public void setSupName(String supName) {
        this.supName = supName;
    }

    /**
     * @return the cntId
     */
    public Long getCntId() {
        return cntId;
    }

    /**
     * @param cntId the cntId to set
     */
    public void setCntId(Long cntId) {
        this.cntId = cntId;
    }

    /**
     * @return the htCode
     */
    public String getHtCode() {
        return htCode;
    }

    /**
     * @param htCode the htCode to set
     */
    public void setHtCode(String htCode) {
        this.htCode = htCode;
    }

    /**
     * @return the htName
     */
    public String getHtName() {
        return htName;
    }

    /**
     * @param htName the htName to set
     */
    public void setHtName(String htName) {
        this.htName = htName;
    }

    /**
     * @return the jyMode
     */
    public String getJyMode() {
        return jyMode;
    }

    /**
     * @param jyMode the jyMode to set
     */
    public void setJyMode(String jyMode) {
        this.jyMode = jyMode;
    }

    /**
     * @return the jsCode
     */
    public String getJsCode() {
        return jsCode;
    }

    /**
     * @param jsCode the jsCode to set
     */
    public void setJsCode(String jsCode) {
        this.jsCode = jsCode;
    }

    /**
     * @return the psCntid
     */
    public Long getPsCntid() {
        return psCntid;
    }

    /**
     * @param psCntid the psCntid to set
     */
    public void setPsCntid(Long psCntid) {
        this.psCntid = psCntid;
    }

    /**
     * @return the psHtCode
     */
    public String getPsHtCode() {
        return psHtCode;
    }

    /**
     * @param psHtCode the psHtCode to set
     */
    public void setPsHtCode(String psHtCode) {
        this.psHtCode = psHtCode;
    }

    /**
     * @return the psHtName
     */
    public String getPsHtName() {
        return psHtName;
    }

    /**
     * @param psHtName the psHtName to set
     */
    public void setPsHtName(String psHtName) {
        this.psHtName = psHtName;
    }

    /**
     * @return the psJyMode
     */
    public String getPsJyMode() {
        return psJyMode;
    }

    /**
     * @param psJyMode the psJyMode to set
     */
    public void setPsJyMode(String psJyMode) {
        this.psJyMode = psJyMode;
    }

    /**
     * @return the psJsCode
     */
    public String getPsJsCode() {
        return psJsCode;
    }

    /**
     * @param psJsCode the psJsCode to set
     */
    public void setPsJsCode(String psJsCode) {
        this.psJsCode = psJsCode;
    }

    /**
     * @return the ckCode
     */
    public String getCkCode() {
        return ckCode;
    }

    /**
     * @param ckCode the ckCode to set
     */
    public void setCkCode(String ckCode) {
        this.ckCode = ckCode;
    }

    /**
     * @return the ckName
     */
    public String getCkName() {
        return ckName;
    }

    /**
     * @param ckName the ckName to set
     */
    public void setCkName(String ckName) {
        this.ckName = ckName;
    }

    /**
     * @return the jhCount
     */
    public Long getJhCount() {
        return jhCount;
    }

    /**
     * @param jhCount the jhCount to set
     */
    public void setJhCount(Long jhCount) {
        this.jhCount = jhCount;
    }

    /**
     * @return the hCost
     */
    public Long gethCost() {
        return hCost;
    }

    /**
     * @param hCost the hCost to set
     */
    public void sethCost(Long hCost) {
        this.hCost = hCost;
    }

    /**
     * @return the wCost
     */
    public Long getwCost() {
        return wCost;
    }

    /**
     * @param wCost the wCost to set
     */
    public void setwCost(Long wCost) {
        this.wCost = wCost;
    }

    /**
     * @return the jtaxTotal
     */
    public Long getJtaxTotal() {
        return jtaxTotal;
    }

    /**
     * @param jtaxTotal the jtaxTotal to set
     */
    public void setJtaxTotal(Long jtaxTotal) {
        this.jtaxTotal = jtaxTotal;
    }

    /**
     * @return the psCost
     */
    public Long getPsCost() {
        return psCost;
    }

    /**
     * @param psCost the psCost to set
     */
    public void setPsCost(Long psCost) {
        this.psCost = psCost;
    }

    /**
     * @return the sTotal
     */
    public Long getsTotal() {
        return sTotal;
    }

    /**
     * @param sTotal the sTotal to set
     */
    public void setsTotal(Long sTotal) {
        this.sTotal = sTotal;
    }

    /**
     * @return the cjTotal
     */
    public Long getCjTotal() {
        return cjTotal;
    }

    /**
     * @param cjTotal the cjTotal to set
     */
    public void setCjTotal(Long cjTotal) {
        this.cjTotal = cjTotal;
    }

    /**
     * @return the refBillType
     */
    public String getRefBillType() {
        return refBillType;
    }

    /**
     * @param refBillType the refBillType to set
     */
    public void setRefBillType(String refBillType) {
        this.refBillType = refBillType;
    }

    /**
     * @return the refBillNo
     */
    public String getRefBillNo() {
        return refBillNo;
    }

    /**
     * @param refBillNo the refBillNo to set
     */
    public void setRefBillNo(String refBillNo) {
        this.refBillNo = refBillNo;
    }

    /**
     * @return the ysRid
     */
    public Long getYsRid() {
        return ysRid;
    }

    /**
     * @param ysRid the ysRid to set
     */
    public void setYsRid(Long ysRid) {
        this.ysRid = ysRid;
    }

    /**
     * @return the ysrCode
     */
    public String getYsrCode() {
        return ysrCode;
    }

    /**
     * @param ysrCode the ysrCode to set
     */
    public void setYsrCode(String ysrCode) {
        this.ysrCode = ysrCode;
    }

    /**
     * @return the ysrName
     */
    public String getYsrName() {
        return ysrName;
    }

    /**
     * @param ysrName the ysrName to set
     */
    public void setYsrName(String ysrName) {
        this.ysrName = ysrName;
    }

    /**
     * @return the isFp
     */
    public String getIsFp() {
        return isFp;
    }

    /**
     * @param isFp the isFp to set
     */
    public void setIsFp(String isFp) {
        this.isFp = isFp;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the dataStatus
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * @param dataStatus the dataStatus to set
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * @return the isYkYs
     */
    public String getIsYkYs() {
        return isYkYs;
    }

    /**
     * @param isYkYs the isYkYs to set
     */
    public void setIsYkYs(String isYkYs) {
        this.isYkYs = isYkYs;
    }

    /**
     * @return the tag
     */
    public String getTag() {
        return tag;
    }

    /**
     * @param tag the tag to set
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * @return the telePhone
     */
    public String getTelePhone() {
        return telePhone;
    }

    /**
     * @param telePhone the telePhone to set
     */
    public void setTelePhone(String telePhone) {
        this.telePhone = telePhone;
    }

    /**
     * @return the fax
     */
    public String getFax() {
        return fax;
    }

    /**
     * @param fax the fax to set
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * @return the linkMan
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * @param linkMan the linkMan to set
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan;
    }

    /**
     * @return the lkmTel
     */
    public String getLkmTel() {
        return lkmTel;
    }

    /**
     * @param lkmTel the lkmTel to set
     */
    public void setLkmTel(String lkmTel) {
        this.lkmTel = lkmTel;
    }

    /**
     * @return the wPsCost
     */
    public Long getwPsCost() {
        return wPsCost;
    }

    /**
     * @param wPsCost the wPsCost to set
     */
    public void setwPsCost(Long wPsCost) {
        this.wPsCost = wPsCost;
    }

    /**
     * @return the xtaxTotal
     */
    public Long getXtaxTotal() {
        return xtaxTotal;
    }

    /**
     * @param xtaxTotal the xtaxTotal to set
     */
    public void setXtaxTotal(Long xtaxTotal) {
        this.xtaxTotal = xtaxTotal;
    }

    /**
     * @return the originType
     */
    public String getOriginType() {
        return originType;
    }

    /**
     * @param originType the originType to set
     */
    public void setOriginType(String originType) {
        this.originType = originType;
    }

    /**
     * @return the pickDate
     */
    public String getPickDate() {
        return pickDate;
    }

    /**
     * @param pickDate the pickDate to set
     */
    public void setPickDate(String pickDate) {
        this.pickDate = pickDate;
    }

    /**
     * @return the fbBillNo
     */
    public String getFbBillNo() {
        return fbBillNo;
    }

    /**
     * @param fbBillNo the fbBillNo to set
     */
    public void setFbBillNo(String fbBillNo) {
        this.fbBillNo = fbBillNo;
    }

    /**
     * @return the fbStatus
     */
    public String getFbStatus() {
        return fbStatus;
    }

    /**
     * @param fbStatus the fbStatus to set
     */
    public void setFbStatus(String fbStatus) {
        this.fbStatus = fbStatus;
    }

    /**
     * @return the shetpCode
     */
    public String getShetpCode() {
        return shetpCode;
    }

    /**
     * @param shetpCode the shetpCode to set
     */
    public void setShetpCode(String shetpCode) {
        this.shetpCode = shetpCode;
    }

    /**
     * @return the shetpName
     */
    public String getShetpName() {
        return shetpName;
    }

    /**
     * @param shetpName the shetpName to set
     */
    public void setShetpName(String shetpName) {
        this.shetpName = shetpName;
    }

    /**
     * @return the currCode
     */
    public String getCurrCode() {
        return currCode;
    }

    /**
     * @param currCode the currCode to set
     */
    public void setCurrCode(String currCode) {
        this.currCode = currCode;
    }

    /**
     * @return the isStdCurr
     */
    public String getIsStdCurr() {
        return isStdCurr;
    }

    /**
     * @param isStdCurr the isStdCurr to set
     */
    public void setIsStdCurr(String isStdCurr) {
        this.isStdCurr = isStdCurr;
    }

    /**
     * @return the exchangErate
     */
    public Long getExchangErate() {
        return exchangErate;
    }

    /**
     * @param exchangErate the exchangErate to set
     */
    public void setExchangErate(Long exchangErate) {
        this.exchangErate = exchangErate;
    }

    /**
     * @return the stlCurrPsCost
     */
    public Long getStlCurrPsCost() {
        return stlCurrPsCost;
    }

    /**
     * @param stlCurrPsCost the stlCurrPsCost to set
     */
    public void setStlCurrPsCost(Long stlCurrPsCost) {
        this.stlCurrPsCost = stlCurrPsCost;
    }

    /**
     * @return the shrId
     */
    public Long getShrId() {
        return shrId;
    }

    /**
     * @param shrId the shrId to set
     */
    public void setShrId(Long shrId) {
        this.shrId = shrId;
    }

    /**
     * @return the shrCode
     */
    public String getShrCode() {
        return shrCode;
    }

    /**
     * @param shrCode the shrCode to set
     */
    public void setShrCode(String shrCode) {
        this.shrCode = shrCode;
    }

    /**
     * @return the shrName
     */
    public String getShrName() {
        return shrName;
    }

    /**
     * @param shrName the shrName to set
     */
    public void setShrName(String shrName) {
        this.shrName = shrName;
    }

    /**
     * @return the shrDate
     */
    public String getShrDate() {
        return shrDate;
    }

    /**
     * @param shrDate the shrDate to set
     */
    public void setShrDate(String shrDate) {
        this.shrDate = shrDate;
    }

    /**
     * @return the reviewMan
     */
    public String getReviewMan() {
        return reviewMan;
    }

    /**
     * @param reviewMan the reviewMan to set
     */
    public void setReviewMan(String reviewMan) {
        this.reviewMan = reviewMan;
    }

    /**
     * @return the mdBillNo
     */
    public String getMdBillNo() {
        return mdBillNo;
    }

    /**
     * @param mdBillNo the mdBillNo to set
     */
    public void setMdBillNo(String mdBillNo) {
        this.mdBillNo = mdBillNo;
    }

    /**
     * @return the qrDate
     */
    public String getQrDate() {
        return qrDate;
    }

    /**
     * @param qrDate the qrDate to set
     */
    public void setQrDate(String qrDate) {
        this.qrDate = qrDate;
    }

    /**
     * @return the qrType
     */
    public String getQrType() {
        return qrType;
    }

    /**
     * @param qrType the qrType to set
     */
    public void setQrType(String qrType) {
        this.qrType = qrType;
    }

    /**
     * @return the qrrId
     */
    public Long getQrrId() {
        return qrrId;
    }

    /**
     * @param qrrId the qrrId to set
     */
    public void setQrrId(Long qrrId) {
        this.qrrId = qrrId;
    }

    /**
     * @return the qrrCode
     */
    public String getQrrCode() {
        return qrrCode;
    }

    /**
     * @param qrrCode the qrrCode to set
     */
    public void setQrrCode(String qrrCode) {
        this.qrrCode = qrrCode;
    }

    /**
     * @return the qrrName
     */
    public String getQrrName() {
        return qrrName;
    }

    /**
     * @param qrrName the qrrName to set
     */
    public void setQrrName(String qrrName) {
        this.qrrName = qrrName;
    }

    /**
     * @return the zbThckCode
     */
    public String getZbThckCode() {
        return zbThckCode;
    }

    /**
     * @param zbThckCode the zbThckCode to set
     */
    public void setZbThckCode(String zbThckCode) {
        this.zbThckCode = zbThckCode;
    }

    /**
     * @return the remark2
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * @param remark2 the remark2 to set
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }

    /**
     * @return the scmqrDate
     */
    public String getScmqrDate() {
        return scmqrDate;
    }

    /**
     * @param scmqrDate the scmqrDate to set
     */
    public void setScmqrDate(String scmqrDate) {
        this.scmqrDate = scmqrDate;
    }

    /**
     * @return the scmqrTime
     */
    public String getScmqrTime() {
        return scmqrTime;
    }

    /**
     * @param scmqrTime the scmqrTime to set
     */
    public void setScmqrTime(String scmqrTime) {
        this.scmqrTime = scmqrTime;
    }

    /**
     * @return the scmqrOpinion
     */
    public String getScmqrOpinion() {
        return scmqrOpinion;
    }

    /**
     * @param scmqrOpinion the scmqrOpinion to set
     */
    public void setScmqrOpinion(String scmqrOpinion) {
        this.scmqrOpinion = scmqrOpinion;
    }
}
