package com.addlove.service.goods.model;

/**
 * 门店退货申请明细表
 * @author lw
 *
 */
public class OrdThApplyBodyModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.BILLNO
     * 单据号
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.SERIALNO
     * 序号
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long serialNo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PLUID
     * 商品ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long pluId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PLUCODE
     * 商品编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String pluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PLUNAME
     * 商品名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String pluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.EXPLUCODE
     * 特征码编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String exPluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.EXPLUNAME
     * 特征码名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String exPluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.BARCODE
     * 商品条码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.SPEC
     * 规格
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.UNIT
     * 单位
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CARGONO
     * 货号
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String carGoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PLUTYPE
     * 商品类型:0-正品  1-赠品  2-促销品  3-不良品
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String pluType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.DEPID
     * 部门Id
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.DEPCODE
     * 部门编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.DEPNAME
     * 部门名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.HJPRICE
     * 含税进价
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double hjPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.WJPRICE
     * 无税进价
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double wjPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.JTAXRATE
     * 进项税率
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double jtaxrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PRICE
     * 售价
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PSPRICE
     * 配送价(直送退货有效，指门店对总部的配送价格，也是门店自己的进货价格)
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double psPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PACKUNIT
     * 包装单位
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String packUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PACKQTY
     * 包装细数
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double packQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PACKCOUNT
     * 包装数量
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double packCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.SGLCOUNT
     * 单件件数
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double sglCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.THCOUNT
     * 数量
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double thCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.HCOST
     * 含税进价金额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double hCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.WCOST
     * 无税进价金额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double wCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.JTAXTOTAL
     * 进项税额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double jTaxTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.STOTAL
     * 售价金额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double sTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CJTOTAL
     * 进销差价
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double cjTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CJRATE
     * 进销差率
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double cjRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.PSCOST
     * 配送金额（直送退货有效）
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double psCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.REMARK
     * 备注
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.HJSTOTAL
     * 含税结算金额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double hjsTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.WJSTOTAL
     * 无税结算金额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double wjsTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.THREASON
     * 退货原因
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String thReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CHECKINFO
     * 审批信息
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String checkInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CHECKUSERID
     * 审批人ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long checkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CHECKUSERCODE
     * 审批人编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String checkUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CHECKUSERNAME
     * 审批人姓名
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String checkUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CHECKDATE
     * 审批日期
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CLSCODE
     * 品类编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String clsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.CLSNAME
     * 品类名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String clsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.ISSELECT
     * 是否选择
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String isSelect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.ETPCODE
     * 供应商编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String etpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYBODY.DSTTYPE
     * 配送属性:0－配送 1－直送 2－越库
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String dstType;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * @return the serialNo
     */
    public Long getSerialNo() {
        return serialNo;
    }

    /**
     * @param serialNo the serialNo to set
     */
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * @return the pluId
     */
    public Long getPluId() {
        return pluId;
    }

    /**
     * @param pluId the pluId to set
     */
    public void setPluId(Long pluId) {
        this.pluId = pluId;
    }

    /**
     * @return the pluCode
     */
    public String getPluCode() {
        return pluCode;
    }

    /**
     * @param pluCode the pluCode to set
     */
    public void setPluCode(String pluCode) {
        this.pluCode = pluCode;
    }

    /**
     * @return the pluName
     */
    public String getPluName() {
        return pluName;
    }

    /**
     * @param pluName the pluName to set
     */
    public void setPluName(String pluName) {
        this.pluName = pluName;
    }

    /**
     * @return the exPluCode
     */
    public String getExPluCode() {
        return exPluCode;
    }

    /**
     * @param exPluCode the exPluCode to set
     */
    public void setExPluCode(String exPluCode) {
        this.exPluCode = exPluCode;
    }

    /**
     * @return the exPluName
     */
    public String getExPluName() {
        return exPluName;
    }

    /**
     * @param exPluName the exPluName to set
     */
    public void setExPluName(String exPluName) {
        this.exPluName = exPluName;
    }

    /**
     * @return the barCode
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * @param barCode the barCode to set
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    /**
     * @return the spec
     */
    public String getSpec() {
        return spec;
    }

    /**
     * @param spec the spec to set
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * @return the unit
     */
    public String getUnit() {
        return unit;
    }

    /**
     * @param unit the unit to set
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * @return the carGoNo
     */
    public String getCarGoNo() {
        return carGoNo;
    }

    /**
     * @param carGoNo the carGoNo to set
     */
    public void setCarGoNo(String carGoNo) {
        this.carGoNo = carGoNo;
    }

    /**
     * @return the pluType
     */
    public String getPluType() {
        return pluType;
    }

    /**
     * @param pluType the pluType to set
     */
    public void setPluType(String pluType) {
        this.pluType = pluType;
    }

    /**
     * @return the depId
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * @param depId the depId to set
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * @return the depName
     */
    public String getDepName() {
        return depName;
    }

    /**
     * @param depName the depName to set
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * @return the hjPrice
     */
    public Double getHjPrice() {
        return hjPrice;
    }

    /**
     * @param hjPrice the hjPrice to set
     */
    public void setHjPrice(Double hjPrice) {
        this.hjPrice = hjPrice;
    }

    /**
     * @return the wjPrice
     */
    public Double getWjPrice() {
        return wjPrice;
    }

    /**
     * @param wjPrice the wjPrice to set
     */
    public void setWjPrice(Double wjPrice) {
        this.wjPrice = wjPrice;
    }

    /**
     * @return the jtaxrate
     */
    public Double getJtaxrate() {
        return jtaxrate;
    }

    /**
     * @param jtaxrate the jtaxrate to set
     */
    public void setJtaxrate(Double jtaxrate) {
        this.jtaxrate = jtaxrate;
    }

    /**
     * @return the price
     */
    public Double getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * @return the psPrice
     */
    public Double getPsPrice() {
        return psPrice;
    }

    /**
     * @param psPrice the psPrice to set
     */
    public void setPsPrice(Double psPrice) {
        this.psPrice = psPrice;
    }

    /**
     * @return the packUnit
     */
    public String getPackUnit() {
        return packUnit;
    }

    /**
     * @param packUnit the packUnit to set
     */
    public void setPackUnit(String packUnit) {
        this.packUnit = packUnit;
    }

    /**
     * @return the packQty
     */
    public Double getPackQty() {
        return packQty;
    }

    /**
     * @param packQty the packQty to set
     */
    public void setPackQty(Double packQty) {
        this.packQty = packQty;
    }

    /**
     * @return the packCount
     */
    public Double getPackCount() {
        return packCount;
    }

    /**
     * @param packCount the packCount to set
     */
    public void setPackCount(Double packCount) {
        this.packCount = packCount;
    }

    /**
     * @return the sglCount
     */
    public Double getSglCount() {
        return sglCount;
    }

    /**
     * @param sglCount the sglCount to set
     */
    public void setSglCount(Double sglCount) {
        this.sglCount = sglCount;
    }

    /**
     * @return the thCount
     */
    public Double getThCount() {
        return thCount;
    }

    /**
     * @param thCount the thCount to set
     */
    public void setThCount(Double thCount) {
        this.thCount = thCount;
    }

    /**
     * @return the hCost
     */
    public Double gethCost() {
        return hCost;
    }

    /**
     * @param hCost the hCost to set
     */
    public void sethCost(Double hCost) {
        this.hCost = hCost;
    }

    /**
     * @return the wCost
     */
    public Double getwCost() {
        return wCost;
    }

    /**
     * @param wCost the wCost to set
     */
    public void setwCost(Double wCost) {
        this.wCost = wCost;
    }

    /**
     * @return the jTaxTotal
     */
    public Double getjTaxTotal() {
        return jTaxTotal;
    }

    /**
     * @param jTaxTotal the jTaxTotal to set
     */
    public void setjTaxTotal(Double jTaxTotal) {
        this.jTaxTotal = jTaxTotal;
    }

    /**
     * @return the sTotal
     */
    public Double getsTotal() {
        return sTotal;
    }

    /**
     * @param sTotal the sTotal to set
     */
    public void setsTotal(Double sTotal) {
        this.sTotal = sTotal;
    }

    /**
     * @return the cjTotal
     */
    public Double getCjTotal() {
        return cjTotal;
    }

    /**
     * @param cjTotal the cjTotal to set
     */
    public void setCjTotal(Double cjTotal) {
        this.cjTotal = cjTotal;
    }

    /**
     * @return the cjRate
     */
    public Double getCjRate() {
        return cjRate;
    }

    /**
     * @param cjRate the cjRate to set
     */
    public void setCjRate(Double cjRate) {
        this.cjRate = cjRate;
    }

    /**
     * @return the psCost
     */
    public Double getPsCost() {
        return psCost;
    }

    /**
     * @param psCost the psCost to set
     */
    public void setPsCost(Double psCost) {
        this.psCost = psCost;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the hjsTotal
     */
    public Double getHjsTotal() {
        return hjsTotal;
    }

    /**
     * @param hjsTotal the hjsTotal to set
     */
    public void setHjsTotal(Double hjsTotal) {
        this.hjsTotal = hjsTotal;
    }

    /**
     * @return the wjsTotal
     */
    public Double getWjsTotal() {
        return wjsTotal;
    }

    /**
     * @param wjsTotal the wjsTotal to set
     */
    public void setWjsTotal(Double wjsTotal) {
        this.wjsTotal = wjsTotal;
    }

    /**
     * @return the thReason
     */
    public String getThReason() {
        return thReason;
    }

    /**
     * @param thReason the thReason to set
     */
    public void setThReason(String thReason) {
        this.thReason = thReason;
    }

    /**
     * @return the checkInfo
     */
    public String getCheckInfo() {
        return checkInfo;
    }

    /**
     * @param checkInfo the checkInfo to set
     */
    public void setCheckInfo(String checkInfo) {
        this.checkInfo = checkInfo;
    }

    /**
     * @return the checkUserId
     */
    public Long getCheckUserId() {
        return checkUserId;
    }

    /**
     * @param checkUserId the checkUserId to set
     */
    public void setCheckUserId(Long checkUserId) {
        this.checkUserId = checkUserId;
    }

    /**
     * @return the checkUserCode
     */
    public String getCheckUserCode() {
        return checkUserCode;
    }

    /**
     * @param checkUserCode the checkUserCode to set
     */
    public void setCheckUserCode(String checkUserCode) {
        this.checkUserCode = checkUserCode;
    }

    /**
     * @return the checkUserName
     */
    public String getCheckUserName() {
        return checkUserName;
    }

    /**
     * @param checkUserName the checkUserName to set
     */
    public void setCheckUserName(String checkUserName) {
        this.checkUserName = checkUserName;
    }

    /**
     * @return the checkDate
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * @param checkDate the checkDate to set
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * @return the clsCode
     */
    public String getClsCode() {
        return clsCode;
    }

    /**
     * @param clsCode the clsCode to set
     */
    public void setClsCode(String clsCode) {
        this.clsCode = clsCode;
    }

    /**
     * @return the clsName
     */
    public String getClsName() {
        return clsName;
    }

    /**
     * @param clsName the clsName to set
     */
    public void setClsName(String clsName) {
        this.clsName = clsName;
    }

    /**
     * @return the isSelect
     */
    public String getIsSelect() {
        return isSelect;
    }

    /**
     * @param isSelect the isSelect to set
     */
    public void setIsSelect(String isSelect) {
        this.isSelect = isSelect;
    }

    /**
     * @return the etpCode
     */
    public String getEtpCode() {
        return etpCode;
    }

    /**
     * @param etpCode the etpCode to set
     */
    public void setEtpCode(String etpCode) {
        this.etpCode = etpCode;
    }

    /**
     * @return the dstType
     */
    public String getDstType() {
        return dstType;
    }

    /**
     * @param dstType the dstType to set
     */
    public void setDstType(String dstType) {
        this.dstType = dstType;
    }
}