package com.addlove.service.goods.model;

/**
 * 门店退货申请主表
 * @author lw
 *
 */
public class OrdThApplyHeadModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.BILLNO
     * 单据号
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.LRDATE
     * 录入日期
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String lrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.USERID
     * 录入人ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.USERCODE
     * 录入人编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.USERNAME
     * 录入人姓名
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ISNEEDTJWL
     * 是否需要提交
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String isNeedTjwl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.TJDATE
     * 提交日期(在配送单提交准备出库时记录)
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String tjDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.TJRID
     * 提交人ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long tjrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.TJRCODE
     * 提交人编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String tjrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.TJRNAME
     * 提交人姓名
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String tjrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.JZDATE
     * 记账日期
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String jzDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.JZRID
     * 记账人ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long jzrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.JZRCODE
     * 记账人编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String jzrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.JZRNAME
     * 记账人姓名
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String jzrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.JZTYPE
     * 记账类型:0-手工;1-系统
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String jzType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.RPTDATE
     * 报表日期
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String rptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.PRNTIMES
     * 打印次数
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long prnTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.PRNDATE
     * 打印时间
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String prnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.TIMEMARK
     * 时间戳
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long timeMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.YWTYPE
     * 业务类型:0911-门店采购退货 0912-门店退货给总部  0913-门店直送退货给供应商 0914-总部采购退货
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String ywType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.YWIOTYPE
     * 内外部业务类型
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String ywIoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ZDRID
     * 制单人Id
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long zdrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ZDRCODE
     * 制单人编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String zdrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ZDRNAME
     * 制单人姓名
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String zdrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.BILLTYPE
     * 单据类型:0-退货返厂；1-验收冲红；2-整单冲红
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.REFBILLTYPE
     * 相关单据类型:0904-物流采购验收；0905-门店采购验收；0906-无采购验收；0907-直送验收；0908-配送验收(整单冲红时使用);
     * 0913-门店直送退货给供应商；2004-配送退货；2003-普通配送；2007-越库配送
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String refBillType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.REFBILLNO
     * 相关单据号
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String refBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ORGCODE
     * 组织编码(用于记录退货的组织)
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ORGNAME
     * 组织名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.INORGCODE
     * 内部组织编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String inOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ZBORGCODE
     * 总部组织编码(当退货类型为0、2时，记录货退给的总部组织。主要对门店有效，可能需要处理往来关系。)
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String zbOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ZBORGNAME
     * 总部组织名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String zbOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.DEPID
     * 部门Id
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.DEPCODE
     * 部门编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.DEPNAME
     * 部门名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.SUPCODE
     * 供应商编码(当退货类型为1、3、4时，记录货退给的供应商)
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String supCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.SUPNAME
     * 供应商名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String supName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CNTID
     * 合同ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long cntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.HTCODE
     * 合同编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String htCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.HTNAME
     * 合同名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String htName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.JYMODE
     * 经营方式:0-经销；1-代销；2-联销
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String jyMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.JSCODE
     * 结算方式编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String jsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.PSCNTID
     * 配送合同ID(直送退货时有效，指门店对总部的配送合同)
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long psCntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.PSHTCODE
     * 配送合同号
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String psHtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.PSHTNAME
     * 配送合同名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String psHtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.PSJYMODE
     * 配送经营方式
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String psJyMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.PSJSCODE
     * 配送结算方式
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String psJsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CKCODE
     * 仓库编码:连锁仓库或者物流逻辑仓库（连锁使用）
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String ckCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CKNAME
     * 仓库名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String ckName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.BGRID
     * 保管员Id
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long bgrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.BGYCODE
     * 保管员编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String bgyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.BGYNAME
     * 保管员姓名
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String bgyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ISZDJPRICE
     * 是否指定进价:0-否;1-是；指定进价时判断库存按照进价进行判断
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String isZdjPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ISZT
     * 是否直退:0-否；1-是；只有直退给供应商时该值为1，其他为0
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String isZt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.DATASTATUS
     * 数据状态:0－录入；1－审批；2－转审；3－提交；4-可记账；9-关闭
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.THCOUNT
     * 退货数量
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double thCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.HCOST
     * 含税进价金额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double hCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.WCOST
     * 无税进价金额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double wCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.JTAXTOTAL
     * 进项税额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double jTaxTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.STOTAL
     * 售价金额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double sTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CJTOTAL
     * 进销差价
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double cjTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.PSCOST
     * 配送金额
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Double psCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.THREASON
     * 退货原因
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String thReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CKMODE
     * 出库方式:0-先进先出 1-后进先出 3-指定批次　物流出库时有效
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String ckMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.REMARK
     * 备注
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CHECKSTATUS
     * 审批状态
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.APPLYSTATUS
     * 申请状态:0-未申请,1-已申请,2-退货中,3-退货完毕,9-驳回
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String applyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CLSCODE
     * 品类编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String clsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CLSNAME
     * 品类名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String clsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CHECKUSERID
     * 审批人ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long checkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CHECKUSERCODE
     * 审批人编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String checkUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CHECKUSERNAME
     * 审批人姓名
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String checkUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CHECKDATE
     * 审批日期
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.THBILLNO
     * 已生成退货单
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String thBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.ISCREATETHBILL
     * 已生成退货单
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String isCreateThBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CREATEUSERID
     * 生成人ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CREATEUSERCODE
     * 生成人编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String createUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CREATEUSERNAME
     * 生成人姓名
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CREATEDATE
     * 生成日期
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.CREATEBILLNO
     * 生成单据号
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String createBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.SUPCKCODE
     * 供应商仓库
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String supCkCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.SUPCKNAME
     * 供应商仓库名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String supCkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.SUPDEPID
     * 供应商部门ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long supDepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.SUPDEPCODE
     * 供应商部门编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String supDepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.SUPDEPNAME
     * 供应商部门名称
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String supdepname;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * @return the lrDate
     */
    public String getLrDate() {
        return lrDate;
    }

    /**
     * @param lrDate the lrDate to set
     */
    public void setLrDate(String lrDate) {
        this.lrDate = lrDate;
    }

    /**
     * @return the userId
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId the userId to set
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return the userCode
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * @param userCode the userCode to set
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return the isNeedTjwl
     */
    public String getIsNeedTjwl() {
        return isNeedTjwl;
    }

    /**
     * @param isNeedTjwl the isNeedTjwl to set
     */
    public void setIsNeedTjwl(String isNeedTjwl) {
        this.isNeedTjwl = isNeedTjwl;
    }

    /**
     * @return the tjDate
     */
    public String getTjDate() {
        return tjDate;
    }

    /**
     * @param tjDate the tjDate to set
     */
    public void setTjDate(String tjDate) {
        this.tjDate = tjDate;
    }

    /**
     * @return the tjrId
     */
    public Long getTjrId() {
        return tjrId;
    }

    /**
     * @param tjrId the tjrId to set
     */
    public void setTjrId(Long tjrId) {
        this.tjrId = tjrId;
    }

    /**
     * @return the tjrCode
     */
    public String getTjrCode() {
        return tjrCode;
    }

    /**
     * @param tjrCode the tjrCode to set
     */
    public void setTjrCode(String tjrCode) {
        this.tjrCode = tjrCode;
    }

    /**
     * @return the tjrName
     */
    public String getTjrName() {
        return tjrName;
    }

    /**
     * @param tjrName the tjrName to set
     */
    public void setTjrName(String tjrName) {
        this.tjrName = tjrName;
    }

    /**
     * @return the jzDate
     */
    public String getJzDate() {
        return jzDate;
    }

    /**
     * @param jzDate the jzDate to set
     */
    public void setJzDate(String jzDate) {
        this.jzDate = jzDate;
    }

    /**
     * @return the jzrId
     */
    public Long getJzrId() {
        return jzrId;
    }

    /**
     * @param jzrId the jzrId to set
     */
    public void setJzrId(Long jzrId) {
        this.jzrId = jzrId;
    }

    /**
     * @return the jzrCode
     */
    public String getJzrCode() {
        return jzrCode;
    }

    /**
     * @param jzrCode the jzrCode to set
     */
    public void setJzrCode(String jzrCode) {
        this.jzrCode = jzrCode;
    }

    /**
     * @return the jzrName
     */
    public String getJzrName() {
        return jzrName;
    }

    /**
     * @param jzrName the jzrName to set
     */
    public void setJzrName(String jzrName) {
        this.jzrName = jzrName;
    }

    /**
     * @return the jzType
     */
    public String getJzType() {
        return jzType;
    }

    /**
     * @param jzType the jzType to set
     */
    public void setJzType(String jzType) {
        this.jzType = jzType;
    }

    /**
     * @return the rptDate
     */
    public String getRptDate() {
        return rptDate;
    }

    /**
     * @param rptDate the rptDate to set
     */
    public void setRptDate(String rptDate) {
        this.rptDate = rptDate;
    }

    /**
     * @return the prnTimes
     */
    public Long getPrnTimes() {
        return prnTimes;
    }

    /**
     * @param prnTimes the prnTimes to set
     */
    public void setPrnTimes(Long prnTimes) {
        this.prnTimes = prnTimes;
    }

    /**
     * @return the prnDate
     */
    public String getPrnDate() {
        return prnDate;
    }

    /**
     * @param prnDate the prnDate to set
     */
    public void setPrnDate(String prnDate) {
        this.prnDate = prnDate;
    }

    /**
     * @return the timeMark
     */
    public Long getTimeMark() {
        return timeMark;
    }

    /**
     * @param timeMark the timeMark to set
     */
    public void setTimeMark(Long timeMark) {
        this.timeMark = timeMark;
    }

    /**
     * @return the ywType
     */
    public String getYwType() {
        return ywType;
    }

    /**
     * @param ywType the ywType to set
     */
    public void setYwType(String ywType) {
        this.ywType = ywType;
    }

    /**
     * @return the ywIoType
     */
    public String getYwIoType() {
        return ywIoType;
    }

    /**
     * @param ywIoType the ywIoType to set
     */
    public void setYwIoType(String ywIoType) {
        this.ywIoType = ywIoType;
    }

    /**
     * @return the zdrId
     */
    public Long getZdrId() {
        return zdrId;
    }

    /**
     * @param zdrId the zdrId to set
     */
    public void setZdrId(Long zdrId) {
        this.zdrId = zdrId;
    }

    /**
     * @return the zdrCode
     */
    public String getZdrCode() {
        return zdrCode;
    }

    /**
     * @param zdrCode the zdrCode to set
     */
    public void setZdrCode(String zdrCode) {
        this.zdrCode = zdrCode;
    }

    /**
     * @return the zdrName
     */
    public String getZdrName() {
        return zdrName;
    }

    /**
     * @param zdrName the zdrName to set
     */
    public void setZdrName(String zdrName) {
        this.zdrName = zdrName;
    }

    /**
     * @return the billType
     */
    public String getBillType() {
        return billType;
    }

    /**
     * @param billType the billType to set
     */
    public void setBillType(String billType) {
        this.billType = billType;
    }

    /**
     * @return the refBillType
     */
    public String getRefBillType() {
        return refBillType;
    }

    /**
     * @param refBillType the refBillType to set
     */
    public void setRefBillType(String refBillType) {
        this.refBillType = refBillType;
    }

    /**
     * @return the refBillNo
     */
    public String getRefBillNo() {
        return refBillNo;
    }

    /**
     * @param refBillNo the refBillNo to set
     */
    public void setRefBillNo(String refBillNo) {
        this.refBillNo = refBillNo;
    }

    /**
     * @return the orgCode
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * @param orgCode the orgCode to set
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * @return the orgName
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * @param orgName the orgName to set
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * @return the inOrgCode
     */
    public String getInOrgCode() {
        return inOrgCode;
    }

    /**
     * @param inOrgCode the inOrgCode to set
     */
    public void setInOrgCode(String inOrgCode) {
        this.inOrgCode = inOrgCode;
    }

    /**
     * @return the zbOrgCode
     */
    public String getZbOrgCode() {
        return zbOrgCode;
    }

    /**
     * @param zbOrgCode the zbOrgCode to set
     */
    public void setZbOrgCode(String zbOrgCode) {
        this.zbOrgCode = zbOrgCode;
    }

    /**
     * @return the zbOrgName
     */
    public String getZbOrgName() {
        return zbOrgName;
    }

    /**
     * @param zbOrgName the zbOrgName to set
     */
    public void setZbOrgName(String zbOrgName) {
        this.zbOrgName = zbOrgName;
    }

    /**
     * @return the depId
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * @param depId the depId to set
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * @return the depName
     */
    public String getDepName() {
        return depName;
    }

    /**
     * @param depName the depName to set
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * @return the supCode
     */
    public String getSupCode() {
        return supCode;
    }

    /**
     * @param supCode the supCode to set
     */
    public void setSupCode(String supCode) {
        this.supCode = supCode;
    }

    /**
     * @return the supName
     */
    public String getSupName() {
        return supName;
    }

    /**
     * @param supName the supName to set
     */
    public void setSupName(String supName) {
        this.supName = supName;
    }

    /**
     * @return the cntId
     */
    public Long getCntId() {
        return cntId;
    }

    /**
     * @param cntId the cntId to set
     */
    public void setCntId(Long cntId) {
        this.cntId = cntId;
    }

    /**
     * @return the htCode
     */
    public String getHtCode() {
        return htCode;
    }

    /**
     * @param htCode the htCode to set
     */
    public void setHtCode(String htCode) {
        this.htCode = htCode;
    }

    /**
     * @return the htName
     */
    public String getHtName() {
        return htName;
    }

    /**
     * @param htName the htName to set
     */
    public void setHtName(String htName) {
        this.htName = htName;
    }

    /**
     * @return the jyMode
     */
    public String getJyMode() {
        return jyMode;
    }

    /**
     * @param jyMode the jyMode to set
     */
    public void setJyMode(String jyMode) {
        this.jyMode = jyMode;
    }

    /**
     * @return the jsCode
     */
    public String getJsCode() {
        return jsCode;
    }

    /**
     * @param jsCode the jsCode to set
     */
    public void setJsCode(String jsCode) {
        this.jsCode = jsCode;
    }

    /**
     * @return the psCntId
     */
    public Long getPsCntId() {
        return psCntId;
    }

    /**
     * @param psCntId the psCntId to set
     */
    public void setPsCntId(Long psCntId) {
        this.psCntId = psCntId;
    }

    /**
     * @return the psHtCode
     */
    public String getPsHtCode() {
        return psHtCode;
    }

    /**
     * @param psHtCode the psHtCode to set
     */
    public void setPsHtCode(String psHtCode) {
        this.psHtCode = psHtCode;
    }

    /**
     * @return the psHtName
     */
    public String getPsHtName() {
        return psHtName;
    }

    /**
     * @param psHtName the psHtName to set
     */
    public void setPsHtName(String psHtName) {
        this.psHtName = psHtName;
    }

    /**
     * @return the psJyMode
     */
    public String getPsJyMode() {
        return psJyMode;
    }

    /**
     * @param psJyMode the psJyMode to set
     */
    public void setPsJyMode(String psJyMode) {
        this.psJyMode = psJyMode;
    }

    /**
     * @return the psJsCode
     */
    public String getPsJsCode() {
        return psJsCode;
    }

    /**
     * @param psJsCode the psJsCode to set
     */
    public void setPsJsCode(String psJsCode) {
        this.psJsCode = psJsCode;
    }

    /**
     * @return the ckCode
     */
    public String getCkCode() {
        return ckCode;
    }

    /**
     * @param ckCode the ckCode to set
     */
    public void setCkCode(String ckCode) {
        this.ckCode = ckCode;
    }

    /**
     * @return the ckName
     */
    public String getCkName() {
        return ckName;
    }

    /**
     * @param ckName the ckName to set
     */
    public void setCkName(String ckName) {
        this.ckName = ckName;
    }

    /**
     * @return the bgrId
     */
    public Long getBgrId() {
        return bgrId;
    }

    /**
     * @param bgrId the bgrId to set
     */
    public void setBgrId(Long bgrId) {
        this.bgrId = bgrId;
    }

    /**
     * @return the bgyCode
     */
    public String getBgyCode() {
        return bgyCode;
    }

    /**
     * @param bgyCode the bgyCode to set
     */
    public void setBgyCode(String bgyCode) {
        this.bgyCode = bgyCode;
    }

    /**
     * @return the bgyName
     */
    public String getBgyName() {
        return bgyName;
    }

    /**
     * @param bgyName the bgyName to set
     */
    public void setBgyName(String bgyName) {
        this.bgyName = bgyName;
    }

    /**
     * @return the isZdjPrice
     */
    public String getIsZdjPrice() {
        return isZdjPrice;
    }

    /**
     * @param isZdjPrice the isZdjPrice to set
     */
    public void setIsZdjPrice(String isZdjPrice) {
        this.isZdjPrice = isZdjPrice;
    }

    /**
     * @return the isZt
     */
    public String getIsZt() {
        return isZt;
    }

    /**
     * @param isZt the isZt to set
     */
    public void setIsZt(String isZt) {
        this.isZt = isZt;
    }

    /**
     * @return the dataStatus
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * @param dataStatus the dataStatus to set
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * @return the thCount
     */
    public Double getThCount() {
        return thCount;
    }

    /**
     * @param thCount the thCount to set
     */
    public void setThCount(Double thCount) {
        this.thCount = thCount;
    }

    /**
     * @return the hCost
     */
    public Double gethCost() {
        return hCost;
    }

    /**
     * @param hCost the hCost to set
     */
    public void sethCost(Double hCost) {
        this.hCost = hCost;
    }

    /**
     * @return the wCost
     */
    public Double getwCost() {
        return wCost;
    }

    /**
     * @param wCost the wCost to set
     */
    public void setwCost(Double wCost) {
        this.wCost = wCost;
    }

    /**
     * @return the jTaxTotal
     */
    public Double getjTaxTotal() {
        return jTaxTotal;
    }

    /**
     * @param jTaxTotal the jTaxTotal to set
     */
    public void setjTaxTotal(Double jTaxTotal) {
        this.jTaxTotal = jTaxTotal;
    }

    /**
     * @return the sTotal
     */
    public Double getsTotal() {
        return sTotal;
    }

    /**
     * @param sTotal the sTotal to set
     */
    public void setsTotal(Double sTotal) {
        this.sTotal = sTotal;
    }

    /**
     * @return the cjTotal
     */
    public Double getCjTotal() {
        return cjTotal;
    }

    /**
     * @param cjTotal the cjTotal to set
     */
    public void setCjTotal(Double cjTotal) {
        this.cjTotal = cjTotal;
    }

    /**
     * @return the psCost
     */
    public Double getPsCost() {
        return psCost;
    }

    /**
     * @param psCost the psCost to set
     */
    public void setPsCost(Double psCost) {
        this.psCost = psCost;
    }

    /**
     * @return the thReason
     */
    public String getThReason() {
        return thReason;
    }

    /**
     * @param thReason the thReason to set
     */
    public void setThReason(String thReason) {
        this.thReason = thReason;
    }

    /**
     * @return the ckMode
     */
    public String getCkMode() {
        return ckMode;
    }

    /**
     * @param ckMode the ckMode to set
     */
    public void setCkMode(String ckMode) {
        this.ckMode = ckMode;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the checkStatus
     */
    public String getCheckStatus() {
        return checkStatus;
    }

    /**
     * @param checkStatus the checkStatus to set
     */
    public void setCheckStatus(String checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * @return the applyStatus
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * @param applyStatus the applyStatus to set
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus;
    }

    /**
     * @return the clsCode
     */
    public String getClsCode() {
        return clsCode;
    }

    /**
     * @param clsCode the clsCode to set
     */
    public void setClsCode(String clsCode) {
        this.clsCode = clsCode;
    }

    /**
     * @return the clsName
     */
    public String getClsName() {
        return clsName;
    }

    /**
     * @param clsName the clsName to set
     */
    public void setClsName(String clsName) {
        this.clsName = clsName;
    }

    /**
     * @return the checkUserId
     */
    public Long getCheckUserId() {
        return checkUserId;
    }

    /**
     * @param checkUserId the checkUserId to set
     */
    public void setCheckUserId(Long checkUserId) {
        this.checkUserId = checkUserId;
    }

    /**
     * @return the checkUserCode
     */
    public String getCheckUserCode() {
        return checkUserCode;
    }

    /**
     * @param checkUserCode the checkUserCode to set
     */
    public void setCheckUserCode(String checkUserCode) {
        this.checkUserCode = checkUserCode;
    }

    /**
     * @return the checkUserName
     */
    public String getCheckUserName() {
        return checkUserName;
    }

    /**
     * @param checkUserName the checkUserName to set
     */
    public void setCheckUserName(String checkUserName) {
        this.checkUserName = checkUserName;
    }

    /**
     * @return the checkDate
     */
    public String getCheckDate() {
        return checkDate;
    }

    /**
     * @param checkDate the checkDate to set
     */
    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * @return the thBillNo
     */
    public String getThBillNo() {
        return thBillNo;
    }

    /**
     * @param thBillNo the thBillNo to set
     */
    public void setThBillNo(String thBillNo) {
        this.thBillNo = thBillNo;
    }

    /**
     * @return the isCreateThBill
     */
    public String getIsCreateThBill() {
        return isCreateThBill;
    }

    /**
     * @param isCreateThBill the isCreateThBill to set
     */
    public void setIsCreateThBill(String isCreateThBill) {
        this.isCreateThBill = isCreateThBill;
    }

    /**
     * @return the createUserId
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * @param createUserId the createUserId to set
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * @return the createUserCode
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * @param createUserCode the createUserCode to set
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode;
    }

    /**
     * @return the createUserName
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * @param createUserName the createUserName to set
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * @return the createDate
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * @param createDate the createDate to set
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * @return the createBillNo
     */
    public String getCreateBillNo() {
        return createBillNo;
    }

    /**
     * @param createBillNo the createBillNo to set
     */
    public void setCreateBillNo(String createBillNo) {
        this.createBillNo = createBillNo;
    }

    /**
     * @return the supCkCode
     */
    public String getSupCkCode() {
        return supCkCode;
    }

    /**
     * @param supCkCode the supCkCode to set
     */
    public void setSupCkCode(String supCkCode) {
        this.supCkCode = supCkCode;
    }

    /**
     * @return the supCkName
     */
    public String getSupCkName() {
        return supCkName;
    }

    /**
     * @param supCkName the supCkName to set
     */
    public void setSupCkName(String supCkName) {
        this.supCkName = supCkName;
    }

    /**
     * @return the supDepId
     */
    public Long getSupDepId() {
        return supDepId;
    }

    /**
     * @param supDepId the supDepId to set
     */
    public void setSupDepId(Long supDepId) {
        this.supDepId = supDepId;
    }

    /**
     * @return the supDepCode
     */
    public String getSupDepCode() {
        return supDepCode;
    }

    /**
     * @param supDepCode the supDepCode to set
     */
    public void setSupDepCode(String supDepCode) {
        this.supDepCode = supDepCode;
    }

    /**
     * @return the supdepname
     */
    public String getSupdepname() {
        return supdepname;
    }

    /**
     * @param supdepname the supdepname to set
     */
    public void setSupdepname(String supdepname) {
        this.supdepname = supdepname;
    }
}