package com.addlove.service.goods.model;

import java.util.List;

/**
 * 退货单主表
 * @author lw
 *
 */
public class OrdThHeadModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.BILLNO
     * 单据号
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.LRDATE
     * 录入日期
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String lrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.USERID
     * 录入人ID
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.USERCODE
     * 录入人编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.USERNAME
     * 录入人姓名
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ISNEEDTJWL
     * 是否需要提交
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String isNeedTjwl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.TJDATE
     * 提交日期
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String tjDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.TJRID
     * 提交人ID
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long tjrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.TJRCODE
     * 提交人编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String tjrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.TJRNAME
     * 提交人姓名
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String tjrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.JZDATE
     * 记账日期
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String jzDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.JZRID
     * 记账人ID
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long jzrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.JZRCODE
     * 记账人编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String jzrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.JZRNAME
     * 记账人姓名
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String jzrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.JZTYPE
     * 记账类型：0-手工；1-系统
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String jzType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.RPTDATE
     * 报表日期
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String rptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.PRNTIMES
     * 打印次数
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long prnTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.PRNDATE
     * 打印时间
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String prnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.TIMEMARK
     * 时间戳
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long timemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.YWTYPE
     * 业务类型：0911-门店采购退货 0912-门店退货给总部  0913-门店直送退货给供应商 0914-总部采购退货
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String ywType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.YWIOTYPE
     * 内外部业务类型：0-内部业务；1-外部业务
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String ywIoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZDRID
     * 制单人Id
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long zdrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZDRCODE
     * 制单人编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String zdrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZDRNAME
     * 制单人姓名
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String zdrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.BILLTYPE
     * 单据类型：0-退货返厂；1-验收冲红；2-整单冲红
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.REFBILLTYPE
     * 相关单据类型：0904-物流采购验收；0905-门店采购验收；0906-无采购验收；0907-直送验收；
     * 0908-配送验收(整单冲红时使用)；0913-门店直送退货给供应商；2004-配送退货；
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String refBillType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.REFBILLNO
     * 相关单据号
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String refBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ORGCODE
     * 组织编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ORGNAME
     * 组织名称
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.INORGCODE
     * 内部组织编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String inOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZBORGCODE
     * 总部组织编码：当退货类型为0、2时，记录货退给的总部组织。主要对门店有效，可能需要处理往来关系。
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String zbOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZBORGNAME
     * 总部组织名称
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String zbOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.DEPID
     * 部门Id：记录退货的部门表头上的部门级别必须与组织的核算级别一致或者比核算级别低，如果核算级别到组织一级则部门不必用户录入由系统自动处理（最好是隐藏），
     * 如果核算到部门，则一张单据只能包含该核算部门的数据。
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.DEPCODE
     * 部门编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.DEPNAME
     * 部门名称
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.SUPCODE
     * 供应商编码：当退货类型为1、3、4时，记录货退给的供应商
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String supCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.SUPNAME
     * 供应商名称
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String supName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.CNTID
     * 合同ID：非直送退货时指退货组织的进货合同；直送退货时指总部组织的进货合同
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long cntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.HTCODE
     * 合同编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String htCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.HTNAME
     * 合同名称
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String htName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.JYMODE
     * 经营方式：0-经销；1-代销；2-联销
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String jyMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.JSCODE
     * 结算方式编码：0-经销结算；1-代销结算；2-联销结算；3-租金结算
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String jsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.PSCNTID
     * 配送合同ID：直送退货时有效，指门店对总部的配送合同
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long psCntId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.PSHTCODE
     * 配送合同号
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String psHtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.PSHTNAME
     * 配送合同名称
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String psHtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.PSJYMODE
     * 配送经营方式
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String psJyMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.PSJSCODE
     * 配送结算方式
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String psJsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.CKCODE
     * 仓库编码：连锁仓库或者物流逻辑仓库（连锁使用）
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String ckCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.CKNAME
     * 仓库名称
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String ckName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.BGRID
     * 保管员Id
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long bgrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.BGYCODE
     * 保管员编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String bgyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.BGYNAME
     * 保管员姓名
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String bgyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ISZDJPRICE
     * 是否指定进价：0-否;1-是；指定进价时判断库存按照进价进行判断
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String isZdJPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ISZT
     * 是否直退：0-否；1-是；只有直退给供应商时该值为1，其他为0
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String isZt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.DATASTATUS
     * 数据状态：0－录入；1－审批；2－转审；3－提交；4-可记账；9-关闭
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.THCOUNT
     * 退货数量
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double thCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.HCOST
     * 含税进价金额
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double hCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.WCOST
     * 无税进价金额
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double wCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.JTAXTOTAL
     * 进项税额
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double jTaxTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.STOTAL
     * 售价金额
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double sTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.CJTOTAL
     * 进销差价
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double cjTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.PSCOST
     * 配送金额：直送验收时使用
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double psCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.THREASON
     * 退货原因
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String thReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.CKMODE
     * 出库方式：0-先进先出 1-后进先出 3-指定批次　物流出库时有效
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String ckMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.WPSTOTAL
     * 无税配送金额：直送验收时使用
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double wpsTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.XTAXTOTAL
     * 销项税额
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double xTaxTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.WLAREACODE
     * 功能区域编码：用来满足指定功能区域出库的情况
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String wlAreaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.WLAREANAME
     * 功能区域名称
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String wlAreaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.TELEPHONE
     * 电话
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.FAX
     * 传真
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.LINKMAN
     * 联系人
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String linkMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.LKMTEL
     * 联系人电话
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String lkmTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.CURRCODE
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String currCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ISSTDCURR
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String isStdCurr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.EXCHANGERATE
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double exchangeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.STLCURRPSCOST
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Double stlCurrPsCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZBDEPID
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long zbDepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZBDEPCODE
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String zbDepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZBDEPNAME
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String zbDepName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZBCKCODE
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String zbCkCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.ZBCKNAME
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String zbCkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.MDBILLNO
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String mdBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.SHRID
     * 审核人ID
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private Long shrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.SHRCODE
     * 审核人编码
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String shrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.SHRNAME
     * 审核人姓名
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String shrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.BILLSTATE
     * 单据状态
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String billState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.APPLYBILLNO
     * 直送退货申请单号
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String applyBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.REMARK
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.REFTHBILLNO
     * 相关退货单号
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String refThBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.QRDATE
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String qrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.QRTIME
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String qrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHHEAD.QROPINION
     *
     * @mbggenerated Thu Jul 11 16:42:43 CST 2019
     */
    private String qrOpinion;
    
    private List<OrdThBodyModel> bodyList;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * @return the lrDate
     */
    public String getLrDate() {
        return lrDate;
    }

    /**
     * @param lrDate the lrDate to set
     */
    public void setLrDate(String lrDate) {
        this.lrDate = lrDate;
    }

    /**
     * @return the userId
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId the userId to set
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return the userCode
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * @param userCode the userCode to set
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return the isNeedTjwl
     */
    public String getIsNeedTjwl() {
        return isNeedTjwl;
    }

    /**
     * @param isNeedTjwl the isNeedTjwl to set
     */
    public void setIsNeedTjwl(String isNeedTjwl) {
        this.isNeedTjwl = isNeedTjwl;
    }

    /**
     * @return the tjDate
     */
    public String getTjDate() {
        return tjDate;
    }

    /**
     * @param tjDate the tjDate to set
     */
    public void setTjDate(String tjDate) {
        this.tjDate = tjDate;
    }

    /**
     * @return the tjrId
     */
    public Long getTjrId() {
        return tjrId;
    }

    /**
     * @param tjrId the tjrId to set
     */
    public void setTjrId(Long tjrId) {
        this.tjrId = tjrId;
    }

    /**
     * @return the tjrCode
     */
    public String getTjrCode() {
        return tjrCode;
    }

    /**
     * @param tjrCode the tjrCode to set
     */
    public void setTjrCode(String tjrCode) {
        this.tjrCode = tjrCode;
    }

    /**
     * @return the tjrName
     */
    public String getTjrName() {
        return tjrName;
    }

    /**
     * @param tjrName the tjrName to set
     */
    public void setTjrName(String tjrName) {
        this.tjrName = tjrName;
    }

    /**
     * @return the jzDate
     */
    public String getJzDate() {
        return jzDate;
    }

    /**
     * @param jzDate the jzDate to set
     */
    public void setJzDate(String jzDate) {
        this.jzDate = jzDate;
    }

    /**
     * @return the jzrId
     */
    public Long getJzrId() {
        return jzrId;
    }

    /**
     * @param jzrId the jzrId to set
     */
    public void setJzrId(Long jzrId) {
        this.jzrId = jzrId;
    }

    /**
     * @return the jzrCode
     */
    public String getJzrCode() {
        return jzrCode;
    }

    /**
     * @param jzrCode the jzrCode to set
     */
    public void setJzrCode(String jzrCode) {
        this.jzrCode = jzrCode;
    }

    /**
     * @return the jzrName
     */
    public String getJzrName() {
        return jzrName;
    }

    /**
     * @param jzrName the jzrName to set
     */
    public void setJzrName(String jzrName) {
        this.jzrName = jzrName;
    }

    /**
     * @return the jzType
     */
    public String getJzType() {
        return jzType;
    }

    /**
     * @param jzType the jzType to set
     */
    public void setJzType(String jzType) {
        this.jzType = jzType;
    }

    /**
     * @return the rptDate
     */
    public String getRptDate() {
        return rptDate;
    }

    /**
     * @param rptDate the rptDate to set
     */
    public void setRptDate(String rptDate) {
        this.rptDate = rptDate;
    }

    /**
     * @return the prnTimes
     */
    public Long getPrnTimes() {
        return prnTimes;
    }

    /**
     * @param prnTimes the prnTimes to set
     */
    public void setPrnTimes(Long prnTimes) {
        this.prnTimes = prnTimes;
    }

    /**
     * @return the prnDate
     */
    public String getPrnDate() {
        return prnDate;
    }

    /**
     * @param prnDate the prnDate to set
     */
    public void setPrnDate(String prnDate) {
        this.prnDate = prnDate;
    }

    /**
     * @return the timemark
     */
    public Long getTimemark() {
        return timemark;
    }

    /**
     * @param timemark the timemark to set
     */
    public void setTimemark(Long timemark) {
        this.timemark = timemark;
    }

    /**
     * @return the ywType
     */
    public String getYwType() {
        return ywType;
    }

    /**
     * @param ywType the ywType to set
     */
    public void setYwType(String ywType) {
        this.ywType = ywType;
    }

    /**
     * @return the ywIoType
     */
    public String getYwIoType() {
        return ywIoType;
    }

    /**
     * @param ywIoType the ywIoType to set
     */
    public void setYwIoType(String ywIoType) {
        this.ywIoType = ywIoType;
    }

    /**
     * @return the zdrId
     */
    public Long getZdrId() {
        return zdrId;
    }

    /**
     * @param zdrId the zdrId to set
     */
    public void setZdrId(Long zdrId) {
        this.zdrId = zdrId;
    }

    /**
     * @return the zdrCode
     */
    public String getZdrCode() {
        return zdrCode;
    }

    /**
     * @param zdrCode the zdrCode to set
     */
    public void setZdrCode(String zdrCode) {
        this.zdrCode = zdrCode;
    }

    /**
     * @return the zdrName
     */
    public String getZdrName() {
        return zdrName;
    }

    /**
     * @param zdrName the zdrName to set
     */
    public void setZdrName(String zdrName) {
        this.zdrName = zdrName;
    }

    /**
     * @return the billType
     */
    public String getBillType() {
        return billType;
    }

    /**
     * @param billType the billType to set
     */
    public void setBillType(String billType) {
        this.billType = billType;
    }

    /**
     * @return the refBillType
     */
    public String getRefBillType() {
        return refBillType;
    }

    /**
     * @param refBillType the refBillType to set
     */
    public void setRefBillType(String refBillType) {
        this.refBillType = refBillType;
    }

    /**
     * @return the refBillNo
     */
    public String getRefBillNo() {
        return refBillNo;
    }

    /**
     * @param refBillNo the refBillNo to set
     */
    public void setRefBillNo(String refBillNo) {
        this.refBillNo = refBillNo;
    }

    /**
     * @return the orgCode
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * @param orgCode the orgCode to set
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * @return the orgName
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * @param orgName the orgName to set
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * @return the inOrgCode
     */
    public String getInOrgCode() {
        return inOrgCode;
    }

    /**
     * @param inOrgCode the inOrgCode to set
     */
    public void setInOrgCode(String inOrgCode) {
        this.inOrgCode = inOrgCode;
    }

    /**
     * @return the zbOrgCode
     */
    public String getZbOrgCode() {
        return zbOrgCode;
    }

    /**
     * @param zbOrgCode the zbOrgCode to set
     */
    public void setZbOrgCode(String zbOrgCode) {
        this.zbOrgCode = zbOrgCode;
    }

    /**
     * @return the zbOrgName
     */
    public String getZbOrgName() {
        return zbOrgName;
    }

    /**
     * @param zbOrgName the zbOrgName to set
     */
    public void setZbOrgName(String zbOrgName) {
        this.zbOrgName = zbOrgName;
    }

    /**
     * @return the depId
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * @param depId the depId to set
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * @return the depName
     */
    public String getDepName() {
        return depName;
    }

    /**
     * @param depName the depName to set
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * @return the supCode
     */
    public String getSupCode() {
        return supCode;
    }

    /**
     * @param supCode the supCode to set
     */
    public void setSupCode(String supCode) {
        this.supCode = supCode;
    }

    /**
     * @return the supName
     */
    public String getSupName() {
        return supName;
    }

    /**
     * @param supName the supName to set
     */
    public void setSupName(String supName) {
        this.supName = supName;
    }

    /**
     * @return the cntId
     */
    public Long getCntId() {
        return cntId;
    }

    /**
     * @param cntId the cntId to set
     */
    public void setCntId(Long cntId) {
        this.cntId = cntId;
    }

    /**
     * @return the htCode
     */
    public String getHtCode() {
        return htCode;
    }

    /**
     * @param htCode the htCode to set
     */
    public void setHtCode(String htCode) {
        this.htCode = htCode;
    }

    /**
     * @return the htName
     */
    public String getHtName() {
        return htName;
    }

    /**
     * @param htName the htName to set
     */
    public void setHtName(String htName) {
        this.htName = htName;
    }

    /**
     * @return the jyMode
     */
    public String getJyMode() {
        return jyMode;
    }

    /**
     * @param jyMode the jyMode to set
     */
    public void setJyMode(String jyMode) {
        this.jyMode = jyMode;
    }

    /**
     * @return the jsCode
     */
    public String getJsCode() {
        return jsCode;
    }

    /**
     * @param jsCode the jsCode to set
     */
    public void setJsCode(String jsCode) {
        this.jsCode = jsCode;
    }

    /**
     * @return the psCntId
     */
    public Long getPsCntId() {
        return psCntId;
    }

    /**
     * @param psCntId the psCntId to set
     */
    public void setPsCntId(Long psCntId) {
        this.psCntId = psCntId;
    }

    /**
     * @return the psHtCode
     */
    public String getPsHtCode() {
        return psHtCode;
    }

    /**
     * @param psHtCode the psHtCode to set
     */
    public void setPsHtCode(String psHtCode) {
        this.psHtCode = psHtCode;
    }

    /**
     * @return the psHtName
     */
    public String getPsHtName() {
        return psHtName;
    }

    /**
     * @param psHtName the psHtName to set
     */
    public void setPsHtName(String psHtName) {
        this.psHtName = psHtName;
    }

    /**
     * @return the psJyMode
     */
    public String getPsJyMode() {
        return psJyMode;
    }

    /**
     * @param psJyMode the psJyMode to set
     */
    public void setPsJyMode(String psJyMode) {
        this.psJyMode = psJyMode;
    }

    /**
     * @return the psJsCode
     */
    public String getPsJsCode() {
        return psJsCode;
    }

    /**
     * @param psJsCode the psJsCode to set
     */
    public void setPsJsCode(String psJsCode) {
        this.psJsCode = psJsCode;
    }

    /**
     * @return the ckCode
     */
    public String getCkCode() {
        return ckCode;
    }

    /**
     * @param ckCode the ckCode to set
     */
    public void setCkCode(String ckCode) {
        this.ckCode = ckCode;
    }

    /**
     * @return the ckName
     */
    public String getCkName() {
        return ckName;
    }

    /**
     * @param ckName the ckName to set
     */
    public void setCkName(String ckName) {
        this.ckName = ckName;
    }

    /**
     * @return the bgrId
     */
    public Long getBgrId() {
        return bgrId;
    }

    /**
     * @param bgrId the bgrId to set
     */
    public void setBgrId(Long bgrId) {
        this.bgrId = bgrId;
    }

    /**
     * @return the bgyCode
     */
    public String getBgyCode() {
        return bgyCode;
    }

    /**
     * @param bgyCode the bgyCode to set
     */
    public void setBgyCode(String bgyCode) {
        this.bgyCode = bgyCode;
    }

    /**
     * @return the bgyName
     */
    public String getBgyName() {
        return bgyName;
    }

    /**
     * @param bgyName the bgyName to set
     */
    public void setBgyName(String bgyName) {
        this.bgyName = bgyName;
    }

    /**
     * @return the isZdJPrice
     */
    public String getIsZdJPrice() {
        return isZdJPrice;
    }

    /**
     * @param isZdJPrice the isZdJPrice to set
     */
    public void setIsZdJPrice(String isZdJPrice) {
        this.isZdJPrice = isZdJPrice;
    }

    /**
     * @return the isZt
     */
    public String getIsZt() {
        return isZt;
    }

    /**
     * @param isZt the isZt to set
     */
    public void setIsZt(String isZt) {
        this.isZt = isZt;
    }

    /**
     * @return the dataStatus
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * @param dataStatus the dataStatus to set
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * @return the thCount
     */
    public Double getThCount() {
        return thCount;
    }

    /**
     * @param thCount the thCount to set
     */
    public void setThCount(Double thCount) {
        this.thCount = thCount;
    }

    /**
     * @return the hCost
     */
    public Double gethCost() {
        return hCost;
    }

    /**
     * @param hCost the hCost to set
     */
    public void sethCost(Double hCost) {
        this.hCost = hCost;
    }

    /**
     * @return the wCost
     */
    public Double getwCost() {
        return wCost;
    }

    /**
     * @param wCost the wCost to set
     */
    public void setwCost(Double wCost) {
        this.wCost = wCost;
    }

    /**
     * @return the jTaxTotal
     */
    public Double getjTaxTotal() {
        return jTaxTotal;
    }

    /**
     * @param jTaxTotal the jTaxTotal to set
     */
    public void setjTaxTotal(Double jTaxTotal) {
        this.jTaxTotal = jTaxTotal;
    }

    /**
     * @return the sTotal
     */
    public Double getsTotal() {
        return sTotal;
    }

    /**
     * @param sTotal the sTotal to set
     */
    public void setsTotal(Double sTotal) {
        this.sTotal = sTotal;
    }

    /**
     * @return the cjTotal
     */
    public Double getCjTotal() {
        return cjTotal;
    }

    /**
     * @param cjTotal the cjTotal to set
     */
    public void setCjTotal(Double cjTotal) {
        this.cjTotal = cjTotal;
    }

    /**
     * @return the psCost
     */
    public Double getPsCost() {
        return psCost;
    }

    /**
     * @param psCost the psCost to set
     */
    public void setPsCost(Double psCost) {
        this.psCost = psCost;
    }

    /**
     * @return the thReason
     */
    public String getThReason() {
        return thReason;
    }

    /**
     * @param thReason the thReason to set
     */
    public void setThReason(String thReason) {
        this.thReason = thReason;
    }

    /**
     * @return the ckMode
     */
    public String getCkMode() {
        return ckMode;
    }

    /**
     * @param ckMode the ckMode to set
     */
    public void setCkMode(String ckMode) {
        this.ckMode = ckMode;
    }

    /**
     * @return the wpsTotal
     */
    public Double getWpsTotal() {
        return wpsTotal;
    }

    /**
     * @param wpsTotal the wpsTotal to set
     */
    public void setWpsTotal(Double wpsTotal) {
        this.wpsTotal = wpsTotal;
    }

    /**
     * @return the xTaxTotal
     */
    public Double getxTaxTotal() {
        return xTaxTotal;
    }

    /**
     * @param xTaxTotal the xTaxTotal to set
     */
    public void setxTaxTotal(Double xTaxTotal) {
        this.xTaxTotal = xTaxTotal;
    }

    /**
     * @return the wlAreaCode
     */
    public String getWlAreaCode() {
        return wlAreaCode;
    }

    /**
     * @param wlAreaCode the wlAreaCode to set
     */
    public void setWlAreaCode(String wlAreaCode) {
        this.wlAreaCode = wlAreaCode;
    }

    /**
     * @return the wlAreaName
     */
    public String getWlAreaName() {
        return wlAreaName;
    }

    /**
     * @param wlAreaName the wlAreaName to set
     */
    public void setWlAreaName(String wlAreaName) {
        this.wlAreaName = wlAreaName;
    }

    /**
     * @return the telephone
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * @param telephone the telephone to set
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * @return the fax
     */
    public String getFax() {
        return fax;
    }

    /**
     * @param fax the fax to set
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * @return the linkMan
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * @param linkMan the linkMan to set
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan;
    }

    /**
     * @return the lkmTel
     */
    public String getLkmTel() {
        return lkmTel;
    }

    /**
     * @param lkmTel the lkmTel to set
     */
    public void setLkmTel(String lkmTel) {
        this.lkmTel = lkmTel;
    }

    /**
     * @return the currCode
     */
    public String getCurrCode() {
        return currCode;
    }

    /**
     * @param currCode the currCode to set
     */
    public void setCurrCode(String currCode) {
        this.currCode = currCode;
    }

    /**
     * @return the isStdCurr
     */
    public String getIsStdCurr() {
        return isStdCurr;
    }

    /**
     * @param isStdCurr the isStdCurr to set
     */
    public void setIsStdCurr(String isStdCurr) {
        this.isStdCurr = isStdCurr;
    }

    /**
     * @return the exchangeRate
     */
    public Double getExchangeRate() {
        return exchangeRate;
    }

    /**
     * @param exchangeRate the exchangeRate to set
     */
    public void setExchangeRate(Double exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * @return the stlCurrPsCost
     */
    public Double getStlCurrPsCost() {
        return stlCurrPsCost;
    }

    /**
     * @param stlCurrPsCost the stlCurrPsCost to set
     */
    public void setStlCurrPsCost(Double stlCurrPsCost) {
        this.stlCurrPsCost = stlCurrPsCost;
    }

    /**
     * @return the zbDepId
     */
    public Long getZbDepId() {
        return zbDepId;
    }

    /**
     * @param zbDepId the zbDepId to set
     */
    public void setZbDepId(Long zbDepId) {
        this.zbDepId = zbDepId;
    }

    /**
     * @return the zbDepCode
     */
    public String getZbDepCode() {
        return zbDepCode;
    }

    /**
     * @param zbDepCode the zbDepCode to set
     */
    public void setZbDepCode(String zbDepCode) {
        this.zbDepCode = zbDepCode;
    }

    /**
     * @return the zbDepName
     */
    public String getZbDepName() {
        return zbDepName;
    }

    /**
     * @param zbDepName the zbDepName to set
     */
    public void setZbDepName(String zbDepName) {
        this.zbDepName = zbDepName;
    }

    /**
     * @return the zbCkCode
     */
    public String getZbCkCode() {
        return zbCkCode;
    }

    /**
     * @param zbCkCode the zbCkCode to set
     */
    public void setZbCkCode(String zbCkCode) {
        this.zbCkCode = zbCkCode;
    }

    /**
     * @return the zbCkName
     */
    public String getZbCkName() {
        return zbCkName;
    }

    /**
     * @param zbCkName the zbCkName to set
     */
    public void setZbCkName(String zbCkName) {
        this.zbCkName = zbCkName;
    }

    /**
     * @return the mdBillNo
     */
    public String getMdBillNo() {
        return mdBillNo;
    }

    /**
     * @param mdBillNo the mdBillNo to set
     */
    public void setMdBillNo(String mdBillNo) {
        this.mdBillNo = mdBillNo;
    }

    /**
     * @return the shrId
     */
    public Long getShrId() {
        return shrId;
    }

    /**
     * @param shrId the shrId to set
     */
    public void setShrId(Long shrId) {
        this.shrId = shrId;
    }

    /**
     * @return the shrCode
     */
    public String getShrCode() {
        return shrCode;
    }

    /**
     * @param shrCode the shrCode to set
     */
    public void setShrCode(String shrCode) {
        this.shrCode = shrCode;
    }

    /**
     * @return the shrName
     */
    public String getShrName() {
        return shrName;
    }

    /**
     * @param shrName the shrName to set
     */
    public void setShrName(String shrName) {
        this.shrName = shrName;
    }

    /**
     * @return the billState
     */
    public String getBillState() {
        return billState;
    }

    /**
     * @param billState the billState to set
     */
    public void setBillState(String billState) {
        this.billState = billState;
    }

    /**
     * @return the applyBillNo
     */
    public String getApplyBillNo() {
        return applyBillNo;
    }

    /**
     * @param applyBillNo the applyBillNo to set
     */
    public void setApplyBillNo(String applyBillNo) {
        this.applyBillNo = applyBillNo;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the refThBillNo
     */
    public String getRefThBillNo() {
        return refThBillNo;
    }

    /**
     * @param refThBillNo the refThBillNo to set
     */
    public void setRefThBillNo(String refThBillNo) {
        this.refThBillNo = refThBillNo;
    }

    /**
     * @return the qrDate
     */
    public String getQrDate() {
        return qrDate;
    }

    /**
     * @param qrDate the qrDate to set
     */
    public void setQrDate(String qrDate) {
        this.qrDate = qrDate;
    }

    /**
     * @return the qrTime
     */
    public String getQrTime() {
        return qrTime;
    }

    /**
     * @param qrTime the qrTime to set
     */
    public void setQrTime(String qrTime) {
        this.qrTime = qrTime;
    }

    /**
     * @return the qrOpinion
     */
    public String getQrOpinion() {
        return qrOpinion;
    }

    /**
     * @param qrOpinion the qrOpinion to set
     */
    public void setQrOpinion(String qrOpinion) {
        this.qrOpinion = qrOpinion;
    }

    /**
     * @return the bodyList
     */
    public List<OrdThBodyModel> getBodyList() {
        return bodyList;
    }

    /**
     * @param bodyList the bodyList to set
     */
    public void setBodyList(List<OrdThBodyModel> bodyList) {
        this.bodyList = bodyList;
    }
}