package com.addlove.service.goods.model;

/**
 * 商品领用及报损设置主表
 * @author lw
 *
 */
public class SkuLyBsSetHeadModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUYHPARASETORG.PROCODE
     * 方案编码
     * @mbggenerated Mon Aug 19 15:29:28 CST 2019
     */
    private String proCode;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUYHPARASETORG.PROCODE
     * 方案名称
     * @mbggenerated Mon Aug 19 15:29:28 CST 2019
     */
    private String proName;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.LRDATE
     * 录入日期
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String lrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.USERID
     * 录入人ID
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.USERCODE
     * 录入人编码
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDTHAPPLYHEAD.USERNAME
     * 录入人姓名
     * @mbggenerated Thu Jun 06 13:47:09 CST 2019
     */
    private String userName;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKULYBSSETHEAD.CTRLTYPE
     * 控制类别
     * @mbggenerated Mon Aug 26 10:18:50 CST 2019
     */
    private String ctrlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKULYBSSETHEAD.CTRLTYPEEX
     * 详细控制类别
     * @mbggenerated Mon Aug 26 10:18:50 CST 2019
     */
    private String ctrlTypeEx;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKULYBSSETHEAD.CTRLTYPEEXNAME
     * 详细通知类别名称
     * @mbggenerated Mon Aug 26 10:18:50 CST 2019
     */
    private String ctrlTypeExName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKULYBSSETHEAD.REMARK
     * 备注
     * @mbggenerated Mon Aug 26 10:18:50 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKULYBSSETHEAD.TIMEMARK
     * 时间戳
     * @mbggenerated Mon Aug 26 10:18:50 CST 2019
     */
    private Long timemark;

    /**
     * @return the proCode
     */
    public String getProCode() {
        return proCode;
    }

    /**
     * @param proCode the proCode to set
     */
    public void setProCode(String proCode) {
        this.proCode = proCode;
    }

    /**
     * @return the proName
     */
    public String getProName() {
        return proName;
    }

    /**
     * @param proName the proName to set
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * @return the lrDate
     */
    public String getLrDate() {
        return lrDate;
    }

    /**
     * @param lrDate the lrDate to set
     */
    public void setLrDate(String lrDate) {
        this.lrDate = lrDate;
    }

    /**
     * @return the userId
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId the userId to set
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * @return the userCode
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * @param userCode the userCode to set
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return the ctrlType
     */
    public String getCtrlType() {
        return ctrlType;
    }

    /**
     * @param ctrlType the ctrlType to set
     */
    public void setCtrlType(String ctrlType) {
        this.ctrlType = ctrlType;
    }

    /**
     * @return the ctrlTypeEx
     */
    public String getCtrlTypeEx() {
        return ctrlTypeEx;
    }

    /**
     * @param ctrlTypeEx the ctrlTypeEx to set
     */
    public void setCtrlTypeEx(String ctrlTypeEx) {
        this.ctrlTypeEx = ctrlTypeEx;
    }

    /**
     * @return the ctrlTypeExName
     */
    public String getCtrlTypeExName() {
        return ctrlTypeExName;
    }

    /**
     * @param ctrlTypeExName the ctrlTypeExName to set
     */
    public void setCtrlTypeExName(String ctrlTypeExName) {
        this.ctrlTypeExName = ctrlTypeExName;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the timemark
     */
    public Long getTimemark() {
        return timemark;
    }

    /**
     * @param timemark the timemark to set
     */
    public void setTimemark(Long timemark) {
        this.timemark = timemark;
    }
}
