package com.addlove.service.goods.model;

/**
 * 商品编码表
 * @author lw
 *
 */
public class SkuPluModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUID
     * 商品ID
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Long pluId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUCODE
     * 商品编码
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String pluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUNAME
     * 商品名称
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String pluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUENAME
     * 商品英文名称
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String pluEName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUABBRNAME
     * 商品简称
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String pluAbbrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUMN
     * 商品助记符
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String plumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.BARCODE
     * 商品条形码
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UNIT
     * 单位
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.SPEC
     * 规格
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUWEIGHT
     * 重量
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double pluWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUHEIGHT
     * 高
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double pluHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLULONG
     * 长
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double pluLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUWIDTH
     * 宽
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double pluWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISMULPACKET
     * 多包装单位:0-否；1-是 如果是，可以在商品包装单位表中记录
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isMulPacket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ORGCODE
     * 引进组织编码
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ORGNAME
     * 引进组织名称
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.CGYID
     * 采购员ID
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Long cgyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.CGYCODE
     * 采购员
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String cgyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.CGYNAME
     * 采购员名称
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String cgyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.CARGONO
     * 货号
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String carGoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PRODUCE
     * 产地
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String produce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.GRADE
     * 等级
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.QUALITY
     * 质地
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String quality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISSEASON
     * 季节性商品:0-否；1-是 对季节性商品需设置销售季节和销售月份属性
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isSeason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.SALESEASON
     * 销售季节:春夏秋冬
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String saleSeason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.BZDAYS
     * 保质期:0表示无保质期限制
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Integer bzDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.CLSID
     * 品类ID
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Long clsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.BRANDCODE
     * 品牌编码
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String brandCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.JTAXCALTYPE
     * 进项税计算类型:0-普通商品；进项税=无税进价金额*进项税率；1-农副产品；进项税=含税进价金额*进项税率
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String jTaxCalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.WJPRICE
     * 无税进价
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double wjPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.HJPRICE
     * 含税进价
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double hjPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.JTAXRATE
     * 进项税率
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Integer jTaxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PRICE
     * 建议零售价
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.XTAXRATE
     * 销项税率
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Integer xTaxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PROMDECIMAL
     * 促销优惠精度:格有效,0表示分；1表示角；2表示元；3表示十元；4表示百元，依次类推。不允许小于0。
     * 这两列从品类上设置，在商品设置时继承；
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double promDecimal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PROMFORMULA
     * 促销价格计算方法:0-不处理;1-四舍五入;2-舍去;3-入上
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String promFormula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.DOTDECIMAL
     * 小数精度
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double dotDecimal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISWEIGHT
     * 称重销售:0-否；1-是
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISCOUTQTY
     * 称重计件:0-否；1-是
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isCoutQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISSELFBRAND
     * 商品管理方式:0-普通商品；1-自有品牌商品；9-门店开放商品
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isSelfBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISKC
     * 管理库存:0-否；1-是
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isKc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISFRESH
     * 灵活控制售价:0-否；1-是
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isFresh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISEXPLUCODE
     * 特征码管理:0-否；1-是
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isExPluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISCURRDAY
     * 日配商品标志
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isCurrDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.JHBFBZDAYS
     * 进货保质期前置天数
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Integer jhBfBzDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PSBFBZDAYS
     * 配送保质期前置天数
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Integer psBfBzDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISNEWPLU
     * 在季:0-否；1-是
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isNewPlu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISACTIVE
     * 可用:0-否；1-是
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.CXINFO
     * 赠品信息
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String cxInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.YWSTATUS
     * 商品状态:0-待批;1-正常;2-预淘汰;3-淘汰
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String ywStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.LRDATE
     * 录入日期
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String lrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.LRUSERID
     * 录入人ID
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Long lrUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.LRUSERCODE
     * 录入人编码
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String lrUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.LRUSERNAME
     * 录入人姓名
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String lrUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ZXDATE
     * 执行日期
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String zxDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ZXUSERID
     * 执行人ID
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Long zxUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ZXUSERCODE
     * 执行人编码
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String zxUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ZXUSERNAME
     * 执行人姓名
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String zxUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP1
     * 老商品编码
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP2
     * 上市日期
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP3
     * 下市日期
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP4
     * 三方对照编码
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP5
     * 自定义属性5
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP6
     * 自定义属性6
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP7
     * 自定义属性7
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP8
     * 自定义属性8
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP9
     * 自定义属性9
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.DATASTATUS
     * 数据状态
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String dataStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.HYPRICE
     * 建议会员价
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Double hyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUCLS
     * 商品类别:0-正常商品；1-辅料；2-牌价；3-加工成品
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String pluCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUMODEL
     * 商品型号
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String pluModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP10
     * 自定义属性10
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP11
     * 自定义属性11
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP12
     * 自定义属性12
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP13
     * 自定义属性13
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.UDP14
     * 自定义属性14
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String udp14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.MATERIALCODE
     * 配送结算价
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String materialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.LRORGCODE
     * 录入组织
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String lrOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.LRORGNAME
     * 录入组织名称
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String lrOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.DATASRC
     * 数据来源：0-新品申请；1-总部录入；2-准新品转入
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String dataSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.MINTHDAYS
     * 退货天数下限
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Integer minThDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.MAXTHDAYS
     * 退货天数上限
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private Integer maxThDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.ISONLINE
     * 上线状态:0-下线；1-上线
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.LINEDATE
     * 上下线日期
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String lineDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPLU.PLUDESC
     * 商品描述
     * @mbggenerated Tue Jun 18 11:01:37 CST 2019
     */
    private String pluDesc;

    /**
     * @return the pluId
     */
    public Long getPluId() {
        return pluId;
    }

    /**
     * @param pluId the pluId to set
     */
    public void setPluId(Long pluId) {
        this.pluId = pluId;
    }

    /**
     * @return the pluCode
     */
    public String getPluCode() {
        return pluCode;
    }

    /**
     * @param pluCode the pluCode to set
     */
    public void setPluCode(String pluCode) {
        this.pluCode = pluCode;
    }

    /**
     * @return the pluName
     */
    public String getPluName() {
        return pluName;
    }

    /**
     * @param pluName the pluName to set
     */
    public void setPluName(String pluName) {
        this.pluName = pluName;
    }

    /**
     * @return the pluEName
     */
    public String getPluEName() {
        return pluEName;
    }

    /**
     * @param pluEName the pluEName to set
     */
    public void setPluEName(String pluEName) {
        this.pluEName = pluEName;
    }

    /**
     * @return the pluAbbrName
     */
    public String getPluAbbrName() {
        return pluAbbrName;
    }

    /**
     * @param pluAbbrName the pluAbbrName to set
     */
    public void setPluAbbrName(String pluAbbrName) {
        this.pluAbbrName = pluAbbrName;
    }

    /**
     * @return the plumn
     */
    public String getPlumn() {
        return plumn;
    }

    /**
     * @param plumn the plumn to set
     */
    public void setPlumn(String plumn) {
        this.plumn = plumn;
    }

    /**
     * @return the barCode
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * @param barCode the barCode to set
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    /**
     * @return the unit
     */
    public String getUnit() {
        return unit;
    }

    /**
     * @param unit the unit to set
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * @return the spec
     */
    public String getSpec() {
        return spec;
    }

    /**
     * @param spec the spec to set
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * @return the pluWeight
     */
    public Double getPluWeight() {
        return pluWeight;
    }

    /**
     * @param pluWeight the pluWeight to set
     */
    public void setPluWeight(Double pluWeight) {
        this.pluWeight = pluWeight;
    }

    /**
     * @return the pluHeight
     */
    public Double getPluHeight() {
        return pluHeight;
    }

    /**
     * @param pluHeight the pluHeight to set
     */
    public void setPluHeight(Double pluHeight) {
        this.pluHeight = pluHeight;
    }

    /**
     * @return the pluLong
     */
    public Double getPluLong() {
        return pluLong;
    }

    /**
     * @param pluLong the pluLong to set
     */
    public void setPluLong(Double pluLong) {
        this.pluLong = pluLong;
    }

    /**
     * @return the pluWidth
     */
    public Double getPluWidth() {
        return pluWidth;
    }

    /**
     * @param pluWidth the pluWidth to set
     */
    public void setPluWidth(Double pluWidth) {
        this.pluWidth = pluWidth;
    }

    /**
     * @return the isMulPacket
     */
    public String getIsMulPacket() {
        return isMulPacket;
    }

    /**
     * @param isMulPacket the isMulPacket to set
     */
    public void setIsMulPacket(String isMulPacket) {
        this.isMulPacket = isMulPacket;
    }

    /**
     * @return the orgCode
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * @param orgCode the orgCode to set
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * @return the orgName
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * @param orgName the orgName to set
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * @return the cgyId
     */
    public Long getCgyId() {
        return cgyId;
    }

    /**
     * @param cgyId the cgyId to set
     */
    public void setCgyId(Long cgyId) {
        this.cgyId = cgyId;
    }

    /**
     * @return the cgyCode
     */
    public String getCgyCode() {
        return cgyCode;
    }

    /**
     * @param cgyCode the cgyCode to set
     */
    public void setCgyCode(String cgyCode) {
        this.cgyCode = cgyCode;
    }

    /**
     * @return the cgyName
     */
    public String getCgyName() {
        return cgyName;
    }

    /**
     * @param cgyName the cgyName to set
     */
    public void setCgyName(String cgyName) {
        this.cgyName = cgyName;
    }

    /**
     * @return the carGoNo
     */
    public String getCarGoNo() {
        return carGoNo;
    }

    /**
     * @param carGoNo the carGoNo to set
     */
    public void setCarGoNo(String carGoNo) {
        this.carGoNo = carGoNo;
    }

    /**
     * @return the produce
     */
    public String getProduce() {
        return produce;
    }

    /**
     * @param produce the produce to set
     */
    public void setProduce(String produce) {
        this.produce = produce;
    }

    /**
     * @return the grade
     */
    public String getGrade() {
        return grade;
    }

    /**
     * @param grade the grade to set
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * @return the quality
     */
    public String getQuality() {
        return quality;
    }

    /**
     * @param quality the quality to set
     */
    public void setQuality(String quality) {
        this.quality = quality;
    }

    /**
     * @return the isSeason
     */
    public String getIsSeason() {
        return isSeason;
    }

    /**
     * @param isSeason the isSeason to set
     */
    public void setIsSeason(String isSeason) {
        this.isSeason = isSeason;
    }

    /**
     * @return the saleSeason
     */
    public String getSaleSeason() {
        return saleSeason;
    }

    /**
     * @param saleSeason the saleSeason to set
     */
    public void setSaleSeason(String saleSeason) {
        this.saleSeason = saleSeason;
    }

    /**
     * @return the bzDays
     */
    public Integer getBzDays() {
        return bzDays;
    }

    /**
     * @param bzDays the bzDays to set
     */
    public void setBzDays(Integer bzDays) {
        this.bzDays = bzDays;
    }

    /**
     * @return the clsId
     */
    public Long getClsId() {
        return clsId;
    }

    /**
     * @param clsId the clsId to set
     */
    public void setClsId(Long clsId) {
        this.clsId = clsId;
    }

    /**
     * @return the brandCode
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * @param brandCode the brandCode to set
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode;
    }

    /**
     * @return the jTaxCalType
     */
    public String getjTaxCalType() {
        return jTaxCalType;
    }

    /**
     * @param jTaxCalType the jTaxCalType to set
     */
    public void setjTaxCalType(String jTaxCalType) {
        this.jTaxCalType = jTaxCalType;
    }

    /**
     * @return the wjPrice
     */
    public Double getWjPrice() {
        return wjPrice;
    }

    /**
     * @param wjPrice the wjPrice to set
     */
    public void setWjPrice(Double wjPrice) {
        this.wjPrice = wjPrice;
    }

    /**
     * @return the hjPrice
     */
    public Double getHjPrice() {
        return hjPrice;
    }

    /**
     * @param hjPrice the hjPrice to set
     */
    public void setHjPrice(Double hjPrice) {
        this.hjPrice = hjPrice;
    }

    /**
     * @return the jTaxRate
     */
    public Integer getjTaxRate() {
        return jTaxRate;
    }

    /**
     * @param jTaxRate the jTaxRate to set
     */
    public void setjTaxRate(Integer jTaxRate) {
        this.jTaxRate = jTaxRate;
    }

    /**
     * @return the price
     */
    public Double getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * @return the xTaxRate
     */
    public Integer getxTaxRate() {
        return xTaxRate;
    }

    /**
     * @param xTaxRate the xTaxRate to set
     */
    public void setxTaxRate(Integer xTaxRate) {
        this.xTaxRate = xTaxRate;
    }

    /**
     * @return the promDecimal
     */
    public Double getPromDecimal() {
        return promDecimal;
    }

    /**
     * @param promDecimal the promDecimal to set
     */
    public void setPromDecimal(Double promDecimal) {
        this.promDecimal = promDecimal;
    }

    /**
     * @return the promFormula
     */
    public String getPromFormula() {
        return promFormula;
    }

    /**
     * @param promFormula the promFormula to set
     */
    public void setPromFormula(String promFormula) {
        this.promFormula = promFormula;
    }

    /**
     * @return the dotDecimal
     */
    public Double getDotDecimal() {
        return dotDecimal;
    }

    /**
     * @param dotDecimal the dotDecimal to set
     */
    public void setDotDecimal(Double dotDecimal) {
        this.dotDecimal = dotDecimal;
    }

    /**
     * @return the isWeight
     */
    public String getIsWeight() {
        return isWeight;
    }

    /**
     * @param isWeight the isWeight to set
     */
    public void setIsWeight(String isWeight) {
        this.isWeight = isWeight;
    }

    /**
     * @return the isCoutQty
     */
    public String getIsCoutQty() {
        return isCoutQty;
    }

    /**
     * @param isCoutQty the isCoutQty to set
     */
    public void setIsCoutQty(String isCoutQty) {
        this.isCoutQty = isCoutQty;
    }

    /**
     * @return the isSelfBrand
     */
    public String getIsSelfBrand() {
        return isSelfBrand;
    }

    /**
     * @param isSelfBrand the isSelfBrand to set
     */
    public void setIsSelfBrand(String isSelfBrand) {
        this.isSelfBrand = isSelfBrand;
    }

    /**
     * @return the isKc
     */
    public String getIsKc() {
        return isKc;
    }

    /**
     * @param isKc the isKc to set
     */
    public void setIsKc(String isKc) {
        this.isKc = isKc;
    }

    /**
     * @return the isFresh
     */
    public String getIsFresh() {
        return isFresh;
    }

    /**
     * @param isFresh the isFresh to set
     */
    public void setIsFresh(String isFresh) {
        this.isFresh = isFresh;
    }

    /**
     * @return the isExPluCode
     */
    public String getIsExPluCode() {
        return isExPluCode;
    }

    /**
     * @param isExPluCode the isExPluCode to set
     */
    public void setIsExPluCode(String isExPluCode) {
        this.isExPluCode = isExPluCode;
    }

    /**
     * @return the isCurrDay
     */
    public String getIsCurrDay() {
        return isCurrDay;
    }

    /**
     * @param isCurrDay the isCurrDay to set
     */
    public void setIsCurrDay(String isCurrDay) {
        this.isCurrDay = isCurrDay;
    }

    /**
     * @return the jhBfBzDays
     */
    public Integer getJhBfBzDays() {
        return jhBfBzDays;
    }

    /**
     * @param jhBfBzDays the jhBfBzDays to set
     */
    public void setJhBfBzDays(Integer jhBfBzDays) {
        this.jhBfBzDays = jhBfBzDays;
    }

    /**
     * @return the psBfBzDays
     */
    public Integer getPsBfBzDays() {
        return psBfBzDays;
    }

    /**
     * @param psBfBzDays the psBfBzDays to set
     */
    public void setPsBfBzDays(Integer psBfBzDays) {
        this.psBfBzDays = psBfBzDays;
    }

    /**
     * @return the isNewPlu
     */
    public String getIsNewPlu() {
        return isNewPlu;
    }

    /**
     * @param isNewPlu the isNewPlu to set
     */
    public void setIsNewPlu(String isNewPlu) {
        this.isNewPlu = isNewPlu;
    }

    /**
     * @return the isActive
     */
    public String getIsActive() {
        return isActive;
    }

    /**
     * @param isActive the isActive to set
     */
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    /**
     * @return the cxInfo
     */
    public String getCxInfo() {
        return cxInfo;
    }

    /**
     * @param cxInfo the cxInfo to set
     */
    public void setCxInfo(String cxInfo) {
        this.cxInfo = cxInfo;
    }

    /**
     * @return the ywStatus
     */
    public String getYwStatus() {
        return ywStatus;
    }

    /**
     * @param ywStatus the ywStatus to set
     */
    public void setYwStatus(String ywStatus) {
        this.ywStatus = ywStatus;
    }

    /**
     * @return the lrDate
     */
    public String getLrDate() {
        return lrDate;
    }

    /**
     * @param lrDate the lrDate to set
     */
    public void setLrDate(String lrDate) {
        this.lrDate = lrDate;
    }

    /**
     * @return the lrUserId
     */
    public Long getLrUserId() {
        return lrUserId;
    }

    /**
     * @param lrUserId the lrUserId to set
     */
    public void setLrUserId(Long lrUserId) {
        this.lrUserId = lrUserId;
    }

    /**
     * @return the lrUserCode
     */
    public String getLrUserCode() {
        return lrUserCode;
    }

    /**
     * @param lrUserCode the lrUserCode to set
     */
    public void setLrUserCode(String lrUserCode) {
        this.lrUserCode = lrUserCode;
    }

    /**
     * @return the lrUserName
     */
    public String getLrUserName() {
        return lrUserName;
    }

    /**
     * @param lrUserName the lrUserName to set
     */
    public void setLrUserName(String lrUserName) {
        this.lrUserName = lrUserName;
    }

    /**
     * @return the zxDate
     */
    public String getZxDate() {
        return zxDate;
    }

    /**
     * @param zxDate the zxDate to set
     */
    public void setZxDate(String zxDate) {
        this.zxDate = zxDate;
    }

    /**
     * @return the zxUserId
     */
    public Long getZxUserId() {
        return zxUserId;
    }

    /**
     * @param zxUserId the zxUserId to set
     */
    public void setZxUserId(Long zxUserId) {
        this.zxUserId = zxUserId;
    }

    /**
     * @return the zxUserCode
     */
    public String getZxUserCode() {
        return zxUserCode;
    }

    /**
     * @param zxUserCode the zxUserCode to set
     */
    public void setZxUserCode(String zxUserCode) {
        this.zxUserCode = zxUserCode;
    }

    /**
     * @return the zxUserName
     */
    public String getZxUserName() {
        return zxUserName;
    }

    /**
     * @param zxUserName the zxUserName to set
     */
    public void setZxUserName(String zxUserName) {
        this.zxUserName = zxUserName;
    }

    /**
     * @return the udp1
     */
    public String getUdp1() {
        return udp1;
    }

    /**
     * @param udp1 the udp1 to set
     */
    public void setUdp1(String udp1) {
        this.udp1 = udp1;
    }

    /**
     * @return the udp2
     */
    public String getUdp2() {
        return udp2;
    }

    /**
     * @param udp2 the udp2 to set
     */
    public void setUdp2(String udp2) {
        this.udp2 = udp2;
    }

    /**
     * @return the udp3
     */
    public String getUdp3() {
        return udp3;
    }

    /**
     * @param udp3 the udp3 to set
     */
    public void setUdp3(String udp3) {
        this.udp3 = udp3;
    }

    /**
     * @return the udp4
     */
    public String getUdp4() {
        return udp4;
    }

    /**
     * @param udp4 the udp4 to set
     */
    public void setUdp4(String udp4) {
        this.udp4 = udp4;
    }

    /**
     * @return the udp5
     */
    public String getUdp5() {
        return udp5;
    }

    /**
     * @param udp5 the udp5 to set
     */
    public void setUdp5(String udp5) {
        this.udp5 = udp5;
    }

    /**
     * @return the udp6
     */
    public String getUdp6() {
        return udp6;
    }

    /**
     * @param udp6 the udp6 to set
     */
    public void setUdp6(String udp6) {
        this.udp6 = udp6;
    }

    /**
     * @return the udp7
     */
    public String getUdp7() {
        return udp7;
    }

    /**
     * @param udp7 the udp7 to set
     */
    public void setUdp7(String udp7) {
        this.udp7 = udp7;
    }

    /**
     * @return the udp8
     */
    public String getUdp8() {
        return udp8;
    }

    /**
     * @param udp8 the udp8 to set
     */
    public void setUdp8(String udp8) {
        this.udp8 = udp8;
    }

    /**
     * @return the udp9
     */
    public String getUdp9() {
        return udp9;
    }

    /**
     * @param udp9 the udp9 to set
     */
    public void setUdp9(String udp9) {
        this.udp9 = udp9;
    }

    /**
     * @return the dataStatus
     */
    public String getDataStatus() {
        return dataStatus;
    }

    /**
     * @param dataStatus the dataStatus to set
     */
    public void setDataStatus(String dataStatus) {
        this.dataStatus = dataStatus;
    }

    /**
     * @return the hyPrice
     */
    public Double getHyPrice() {
        return hyPrice;
    }

    /**
     * @param hyPrice the hyPrice to set
     */
    public void setHyPrice(Double hyPrice) {
        this.hyPrice = hyPrice;
    }

    /**
     * @return the pluCls
     */
    public String getPluCls() {
        return pluCls;
    }

    /**
     * @param pluCls the pluCls to set
     */
    public void setPluCls(String pluCls) {
        this.pluCls = pluCls;
    }

    /**
     * @return the pluModel
     */
    public String getPluModel() {
        return pluModel;
    }

    /**
     * @param pluModel the pluModel to set
     */
    public void setPluModel(String pluModel) {
        this.pluModel = pluModel;
    }

    /**
     * @return the udp10
     */
    public String getUdp10() {
        return udp10;
    }

    /**
     * @param udp10 the udp10 to set
     */
    public void setUdp10(String udp10) {
        this.udp10 = udp10;
    }

    /**
     * @return the udp11
     */
    public String getUdp11() {
        return udp11;
    }

    /**
     * @param udp11 the udp11 to set
     */
    public void setUdp11(String udp11) {
        this.udp11 = udp11;
    }

    /**
     * @return the udp12
     */
    public String getUdp12() {
        return udp12;
    }

    /**
     * @param udp12 the udp12 to set
     */
    public void setUdp12(String udp12) {
        this.udp12 = udp12;
    }

    /**
     * @return the udp13
     */
    public String getUdp13() {
        return udp13;
    }

    /**
     * @param udp13 the udp13 to set
     */
    public void setUdp13(String udp13) {
        this.udp13 = udp13;
    }

    /**
     * @return the udp14
     */
    public String getUdp14() {
        return udp14;
    }

    /**
     * @param udp14 the udp14 to set
     */
    public void setUdp14(String udp14) {
        this.udp14 = udp14;
    }

    /**
     * @return the materialCode
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * @param materialCode the materialCode to set
     */
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode;
    }

    /**
     * @return the lrOrgCode
     */
    public String getLrOrgCode() {
        return lrOrgCode;
    }

    /**
     * @param lrOrgCode the lrOrgCode to set
     */
    public void setLrOrgCode(String lrOrgCode) {
        this.lrOrgCode = lrOrgCode;
    }

    /**
     * @return the lrOrgName
     */
    public String getLrOrgName() {
        return lrOrgName;
    }

    /**
     * @param lrOrgName the lrOrgName to set
     */
    public void setLrOrgName(String lrOrgName) {
        this.lrOrgName = lrOrgName;
    }

    /**
     * @return the dataSrc
     */
    public String getDataSrc() {
        return dataSrc;
    }

    /**
     * @param dataSrc the dataSrc to set
     */
    public void setDataSrc(String dataSrc) {
        this.dataSrc = dataSrc;
    }

    /**
     * @return the minThDays
     */
    public Integer getMinThDays() {
        return minThDays;
    }

    /**
     * @param minThDays the minThDays to set
     */
    public void setMinThDays(Integer minThDays) {
        this.minThDays = minThDays;
    }

    /**
     * @return the maxThDays
     */
    public Integer getMaxThDays() {
        return maxThDays;
    }

    /**
     * @param maxThDays the maxThDays to set
     */
    public void setMaxThDays(Integer maxThDays) {
        this.maxThDays = maxThDays;
    }

    /**
     * @return the isOnline
     */
    public String getIsOnline() {
        return isOnline;
    }

    /**
     * @param isOnline the isOnline to set
     */
    public void setIsOnline(String isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * @return the lineDate
     */
    public String getLineDate() {
        return lineDate;
    }

    /**
     * @param lineDate the lineDate to set
     */
    public void setLineDate(String lineDate) {
        this.lineDate = lineDate;
    }

    /**
     * @return the pluDesc
     */
    public String getPluDesc() {
        return pluDesc;
    }

    /**
     * @param pluDesc the pluDesc to set
     */
    public void setPluDesc(String pluDesc) {
        this.pluDesc = pluDesc;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int code = pluId.hashCode();
        code = 31 * code + pluName.hashCode();
        return code;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (null == obj || getClass() != obj.getClass()) {
            return false;
        }
        SkuPluModel skuPluModel = (SkuPluModel) obj;
        if (!pluId.equals(skuPluModel.pluId)) {
            return false;
        }
        return pluName.equals(skuPluModel.pluName);
    }
}
