package com.addlove.service.goods.model;

/**
 * 组织商品盘点周期方案
 * @author lw
 *
 */
public class SkuPdCSOrgModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.ORGCODE
     * 组织编码
     * @mbggenerated Fri Aug 02 10:50:01 CST 2019
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPDCYCLESCHEME.GRPNO
     * 方案编码
     * @mbggenerated Fri Aug 02 11:49:05 CST 2019
     */
    private String grpNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPDCYCLESCHEME.UPTDATE
     * 修改时间
     * @mbggenerated Fri Aug 02 11:49:05 CST 2019
     */
    private String uptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPDCYCLESCHEME.MODIFYUSERID
     * 修改人ID
     * @mbggenerated Fri Aug 02 11:49:05 CST 2019
     */
    private Long modifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUPDCYCLESCHEME.USERCODE
     * 用户编码
     * @mbggenerated Fri Aug 02 11:49:05 CST 2019
     */
    private String userCode;

    /**
     * @return the orgCode
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * @param orgCode the orgCode to set
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * @return the grpNo
     */
    public String getGrpNo() {
        return grpNo;
    }

    /**
     * @param grpNo the grpNo to set
     */
    public void setGrpNo(String grpNo) {
        this.grpNo = grpNo;
    }

    /**
     * @return the uptDate
     */
    public String getUptDate() {
        return uptDate;
    }

    /**
     * @param uptDate the uptDate to set
     */
    public void setUptDate(String uptDate) {
        this.uptDate = uptDate;
    }

    /**
     * @return the modifyUserId
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * @param modifyUserId the modifyUserId to set
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * @return the userCode
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * @param userCode the userCode to set
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
}