package com.addlove.service.goods.model;

/**
 * 商品要货参数设置明细表
 * @author lw
 *
 */
public class SkuYhPSBodyModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUYHPARASETORG.PROCODE
     * 方案编码
     * @mbggenerated Mon Aug 19 15:29:28 CST 2019
     */
    private String proCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUYHPARASETORG.SERIALNO
     * 序号
     * @mbggenerated Mon Aug 19 15:29:28 CST 2019
     */
    private Long serialNo;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUID
     * 商品Id
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long pluId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUCODE
     * 商品编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String pluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUNAME
     * 商品名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String pluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUYHPARASETBODY.MINCOUNT
     * 最小要货量
     * @mbggenerated Mon Aug 19 15:29:28 CST 2019
     */
    private Double minCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUYHPARASETBODY.MAXCOUNT
     * 最大要货量
     * @mbggenerated Mon Aug 19 15:29:28 CST 2019
     */
    private Double maxCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUYHPARASETBODY.TIMES
     * 要货倍数
     * @mbggenerated Mon Aug 19 15:29:28 CST 2019
     */
    private Double times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSKUYHPARASETBODY.REMARK
     * 备注
     * @mbggenerated Mon Aug 19 15:29:28 CST 2019
     */
    private String remark;

    /**
     * @return the proCode
     */
    public String getProCode() {
        return proCode;
    }

    /**
     * @param proCode the proCode to set
     */
    public void setProCode(String proCode) {
        this.proCode = proCode;
    }

    /**
     * @return the serialNo
     */
    public Long getSerialNo() {
        return serialNo;
    }

    /**
     * @param serialNo the serialNo to set
     */
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * @return the pluId
     */
    public Long getPluId() {
        return pluId;
    }

    /**
     * @param pluId the pluId to set
     */
    public void setPluId(Long pluId) {
        this.pluId = pluId;
    }

    /**
     * @return the pluCode
     */
    public String getPluCode() {
        return pluCode;
    }

    /**
     * @param pluCode the pluCode to set
     */
    public void setPluCode(String pluCode) {
        this.pluCode = pluCode;
    }

    /**
     * @return the pluName
     */
    public String getPluName() {
        return pluName;
    }

    /**
     * @param pluName the pluName to set
     */
    public void setPluName(String pluName) {
        this.pluName = pluName;
    }

    /**
     * @return the minCount
     */
    public Double getMinCount() {
        return minCount;
    }

    /**
     * @param minCount the minCount to set
     */
    public void setMinCount(Double minCount) {
        this.minCount = minCount;
    }

    /**
     * @return the maxCount
     */
    public Double getMaxCount() {
        return maxCount;
    }

    /**
     * @param maxCount the maxCount to set
     */
    public void setMaxCount(Double maxCount) {
        this.maxCount = maxCount;
    }

    /**
     * @return the times
     */
    public Double getTimes() {
        return times;
    }

    /**
     * @param times the times to set
     */
    public void setTimes(Double times) {
        this.times = times;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}