package com.addlove.service.goods.model;

/**
 * 调拨明细表
 * @author lw
 *
 */
public class StkDbBodyModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.BILLNO
     * 单据号
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.SERIALNO
     * 序号
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long serialNo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUID
     * 商品Id
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long pluId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.EXPLUCODE
     * 特征码编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String exPluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.EXPLUNAME
     * 特征码名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String exPluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUCODE
     * 商品编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String pluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUNAME
     * 商品名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String pluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.BARCODE
     * 商品条码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.SPEC
     * 规格
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.UNIT
     * 单位
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PACKUNIT
     * 包装单位
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String packUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PACKQTY
     * 包装细数
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double packQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PACKCOUNT
     * 包装数量
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double packCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.SGLCOUNT
     * 单件件数
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double sglCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.DBCOUNT
     * 调拨数量
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double dbCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUTYPE
     * 商品类型:0-正品；1-赠品；2-促销品；3-不良品；
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String pluType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.HJPRICE
     * 调出含税进价
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double hjPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.WJPRICE
     * 调出无税进价
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double wjPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PRICE
     * 售价
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.JTAXRATE
     * 进项税率
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double jTaxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.HCOST
     * 调出含税进价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double hCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.WCOST
     * 调出无税进价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double wCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.REMARK
     * 备注
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.SHDEPID
     * 调入部门ID
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long shDepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.SHDEPCODE
     * 调入部门编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String shDepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.SHDEPNAME
     * 调入部门名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String shDepName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.RHCOST
     * 调入含税进价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double rhCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.RWCOST
     * 调入无税进价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double rwCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.OUTKWCODE
     * 调出库位编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String outKwCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.INKWCODE
     * 调入库位编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String inKwCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.STOTAL
     * 售价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double sTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.RHJPRICE
     * 调入含税进价
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double rhJPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.RWJPRICE
     * 调入无税进价
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Double rwJPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.CARGONO
     * 货号
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String carGoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.TOSERIALNO
     * 序号参照
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long toSerialNo;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * @return the serialNo
     */
    public Long getSerialNo() {
        return serialNo;
    }

    /**
     * @param serialNo the serialNo to set
     */
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * @return the pluId
     */
    public Long getPluId() {
        return pluId;
    }

    /**
     * @param pluId the pluId to set
     */
    public void setPluId(Long pluId) {
        this.pluId = pluId;
    }

    /**
     * @return the exPluCode
     */
    public String getExPluCode() {
        return exPluCode;
    }

    /**
     * @param exPluCode the exPluCode to set
     */
    public void setExPluCode(String exPluCode) {
        this.exPluCode = exPluCode;
    }

    /**
     * @return the exPluName
     */
    public String getExPluName() {
        return exPluName;
    }

    /**
     * @param exPluName the exPluName to set
     */
    public void setExPluName(String exPluName) {
        this.exPluName = exPluName;
    }

    /**
     * @return the pluCode
     */
    public String getPluCode() {
        return pluCode;
    }

    /**
     * @param pluCode the pluCode to set
     */
    public void setPluCode(String pluCode) {
        this.pluCode = pluCode;
    }

    /**
     * @return the pluName
     */
    public String getPluName() {
        return pluName;
    }

    /**
     * @param pluName the pluName to set
     */
    public void setPluName(String pluName) {
        this.pluName = pluName;
    }

    /**
     * @return the barCode
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * @param barCode the barCode to set
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    /**
     * @return the spec
     */
    public String getSpec() {
        return spec;
    }

    /**
     * @param spec the spec to set
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * @return the unit
     */
    public String getUnit() {
        return unit;
    }

    /**
     * @param unit the unit to set
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * @return the packUnit
     */
    public String getPackUnit() {
        return packUnit;
    }

    /**
     * @param packUnit the packUnit to set
     */
    public void setPackUnit(String packUnit) {
        this.packUnit = packUnit;
    }

    /**
     * @return the packQty
     */
    public Double getPackQty() {
        return packQty;
    }

    /**
     * @param packQty the packQty to set
     */
    public void setPackQty(Double packQty) {
        this.packQty = packQty;
    }

    /**
     * @return the packCount
     */
    public Double getPackCount() {
        return packCount;
    }

    /**
     * @param packCount the packCount to set
     */
    public void setPackCount(Double packCount) {
        this.packCount = packCount;
    }

    /**
     * @return the sglCount
     */
    public Double getSglCount() {
        return sglCount;
    }

    /**
     * @param sglCount the sglCount to set
     */
    public void setSglCount(Double sglCount) {
        this.sglCount = sglCount;
    }

    /**
     * @return the dbCount
     */
    public Double getDbCount() {
        return dbCount;
    }

    /**
     * @param dbCount the dbCount to set
     */
    public void setDbCount(Double dbCount) {
        this.dbCount = dbCount;
    }

    /**
     * @return the pluType
     */
    public String getPluType() {
        return pluType;
    }

    /**
     * @param pluType the pluType to set
     */
    public void setPluType(String pluType) {
        this.pluType = pluType;
    }

    /**
     * @return the hjPrice
     */
    public Double getHjPrice() {
        return hjPrice;
    }

    /**
     * @param hjPrice the hjPrice to set
     */
    public void setHjPrice(Double hjPrice) {
        this.hjPrice = hjPrice;
    }

    /**
     * @return the wjPrice
     */
    public Double getWjPrice() {
        return wjPrice;
    }

    /**
     * @param wjPrice the wjPrice to set
     */
    public void setWjPrice(Double wjPrice) {
        this.wjPrice = wjPrice;
    }

    /**
     * @return the price
     */
    public Double getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * @return the jTaxRate
     */
    public Double getjTaxRate() {
        return jTaxRate;
    }

    /**
     * @param jTaxRate the jTaxRate to set
     */
    public void setjTaxRate(Double jTaxRate) {
        this.jTaxRate = jTaxRate;
    }

    /**
     * @return the hCost
     */
    public Double gethCost() {
        return hCost;
    }

    /**
     * @param hCost the hCost to set
     */
    public void sethCost(Double hCost) {
        this.hCost = hCost;
    }

    /**
     * @return the wCost
     */
    public Double getwCost() {
        return wCost;
    }

    /**
     * @param wCost the wCost to set
     */
    public void setwCost(Double wCost) {
        this.wCost = wCost;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the shDepId
     */
    public Long getShDepId() {
        return shDepId;
    }

    /**
     * @param shDepId the shDepId to set
     */
    public void setShDepId(Long shDepId) {
        this.shDepId = shDepId;
    }

    /**
     * @return the shDepCode
     */
    public String getShDepCode() {
        return shDepCode;
    }

    /**
     * @param shDepCode the shDepCode to set
     */
    public void setShDepCode(String shDepCode) {
        this.shDepCode = shDepCode;
    }

    /**
     * @return the shDepName
     */
    public String getShDepName() {
        return shDepName;
    }

    /**
     * @param shDepName the shDepName to set
     */
    public void setShDepName(String shDepName) {
        this.shDepName = shDepName;
    }

    /**
     * @return the rhCost
     */
    public Double getRhCost() {
        return rhCost;
    }

    /**
     * @param rhCost the rhCost to set
     */
    public void setRhCost(Double rhCost) {
        this.rhCost = rhCost;
    }

    /**
     * @return the rwCost
     */
    public Double getRwCost() {
        return rwCost;
    }

    /**
     * @param rwCost the rwCost to set
     */
    public void setRwCost(Double rwCost) {
        this.rwCost = rwCost;
    }

    /**
     * @return the outKwCode
     */
    public String getOutKwCode() {
        return outKwCode;
    }

    /**
     * @param outKwCode the outKwCode to set
     */
    public void setOutKwCode(String outKwCode) {
        this.outKwCode = outKwCode;
    }

    /**
     * @return the inKwCode
     */
    public String getInKwCode() {
        return inKwCode;
    }

    /**
     * @param inKwCode the inKwCode to set
     */
    public void setInKwCode(String inKwCode) {
        this.inKwCode = inKwCode;
    }

    /**
     * @return the sTotal
     */
    public Double getsTotal() {
        return sTotal;
    }

    /**
     * @param sTotal the sTotal to set
     */
    public void setsTotal(Double sTotal) {
        this.sTotal = sTotal;
    }

    /**
     * @return the rhJPrice
     */
    public Double getRhJPrice() {
        return rhJPrice;
    }

    /**
     * @param rhJPrice the rhJPrice to set
     */
    public void setRhJPrice(Double rhJPrice) {
        this.rhJPrice = rhJPrice;
    }

    /**
     * @return the rwJPrice
     */
    public Double getRwJPrice() {
        return rwJPrice;
    }

    /**
     * @param rwJPrice the rwJPrice to set
     */
    public void setRwJPrice(Double rwJPrice) {
        this.rwJPrice = rwJPrice;
    }

    /**
     * @return the carGoNo
     */
    public String getCarGoNo() {
        return carGoNo;
    }

    /**
     * @param carGoNo the carGoNo to set
     */
    public void setCarGoNo(String carGoNo) {
        this.carGoNo = carGoNo;
    }

    /**
     * @return the toSerialNo
     */
    public Long getToSerialNo() {
        return toSerialNo;
    }

    /**
     * @param toSerialNo the toSerialNo to set
     */
    public void setToSerialNo(Long toSerialNo) {
        this.toSerialNo = toSerialNo;
    }
}
