package com.addlove.service.goods.model;

/**
 * 生日蛋糕加工单商品明细表
 * @author lw
 *
 */
public class WslCakeBillPluTPModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.BILLNO
     * 单据号
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.SERIALNO
     * 序号
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long serialNo;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUID
     * 商品Id
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long pluId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUCODE
     * 商品编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String pluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.PLUNAME
     * 商品名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String pluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.EXPLUCODE
     * 特征码编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String exPluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.EXPLUNAME
     * 特征码名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String exPluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBBODY.BARCODE
     * 商品条码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.SPEC
     *
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.UNIT
     *
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.PLUQTY
     * 数量
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private Double pluQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.PRICE
     *
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.YHPRICE
     * 优惠价
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private Double yhPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.DSCCOUNT
     * 折扣率
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private Double dscCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.PLUDSC
     * 优惠金额
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private Double pluDsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.PLUTOTAL
     * 实收金额
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private Double pluTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.PLUDSCTYPE
     * 商品优惠类型:0-赠送1-手工优惠2-分组优惠3-单品优惠（无单品优惠类型）4-批量优惠5-普通限量6-会员价9-会员限量
     * A-满加送优惠B-满减优惠C-超量优惠D-偶数促销E-买赠促销F-组合促销G-单品优惠H-单品打折I-免费续杯J-第二件特价K-整单打折L-满送
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private String pluDscType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.FONTTYPE
     * 字形
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private String fontType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.REMARK
     * 备注
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.CLSCODE
     *
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private String clsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TWSLCAKEBILLPLU_TOPOS.DEPCODE
     *
     * @mbggenerated Mon Sep 02 11:23:47 CST 2019
     */
    private String depCode;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }

    /**
     * @return the serialNo
     */
    public Long getSerialNo() {
        return serialNo;
    }

    /**
     * @param serialNo the serialNo to set
     */
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * @return the pluId
     */
    public Long getPluId() {
        return pluId;
    }

    /**
     * @param pluId the pluId to set
     */
    public void setPluId(Long pluId) {
        this.pluId = pluId;
    }

    /**
     * @return the pluCode
     */
    public String getPluCode() {
        return pluCode;
    }

    /**
     * @param pluCode the pluCode to set
     */
    public void setPluCode(String pluCode) {
        this.pluCode = pluCode;
    }

    /**
     * @return the pluName
     */
    public String getPluName() {
        return pluName;
    }

    /**
     * @param pluName the pluName to set
     */
    public void setPluName(String pluName) {
        this.pluName = pluName;
    }

    /**
     * @return the exPluCode
     */
    public String getExPluCode() {
        return exPluCode;
    }

    /**
     * @param exPluCode the exPluCode to set
     */
    public void setExPluCode(String exPluCode) {
        this.exPluCode = exPluCode;
    }

    /**
     * @return the exPluName
     */
    public String getExPluName() {
        return exPluName;
    }

    /**
     * @param exPluName the exPluName to set
     */
    public void setExPluName(String exPluName) {
        this.exPluName = exPluName;
    }

    /**
     * @return the barCode
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * @param barCode the barCode to set
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    /**
     * @return the spec
     */
    public String getSpec() {
        return spec;
    }

    /**
     * @param spec the spec to set
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * @return the unit
     */
    public String getUnit() {
        return unit;
    }

    /**
     * @param unit the unit to set
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * @return the pluQty
     */
    public Double getPluQty() {
        return pluQty;
    }

    /**
     * @param pluQty the pluQty to set
     */
    public void setPluQty(Double pluQty) {
        this.pluQty = pluQty;
    }

    /**
     * @return the price
     */
    public Double getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * @return the yhPrice
     */
    public Double getYhPrice() {
        return yhPrice;
    }

    /**
     * @param yhPrice the yhPrice to set
     */
    public void setYhPrice(Double yhPrice) {
        this.yhPrice = yhPrice;
    }

    /**
     * @return the dscCount
     */
    public Double getDscCount() {
        return dscCount;
    }

    /**
     * @param dscCount the dscCount to set
     */
    public void setDscCount(Double dscCount) {
        this.dscCount = dscCount;
    }

    /**
     * @return the pluDsc
     */
    public Double getPluDsc() {
        return pluDsc;
    }

    /**
     * @param pluDsc the pluDsc to set
     */
    public void setPluDsc(Double pluDsc) {
        this.pluDsc = pluDsc;
    }

    /**
     * @return the pluTotal
     */
    public Double getPluTotal() {
        return pluTotal;
    }

    /**
     * @param pluTotal the pluTotal to set
     */
    public void setPluTotal(Double pluTotal) {
        this.pluTotal = pluTotal;
    }

    /**
     * @return the pluDscType
     */
    public String getPluDscType() {
        return pluDscType;
    }

    /**
     * @param pluDscType the pluDscType to set
     */
    public void setPluDscType(String pluDscType) {
        this.pluDscType = pluDscType;
    }

    /**
     * @return the fontType
     */
    public String getFontType() {
        return fontType;
    }

    /**
     * @param fontType the fontType to set
     */
    public void setFontType(String fontType) {
        this.fontType = fontType;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the clsCode
     */
    public String getClsCode() {
        return clsCode;
    }

    /**
     * @param clsCode the clsCode to set
     */
    public void setClsCode(String clsCode) {
        this.clsCode = clsCode;
    }

    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }
}
