package com.addlove.service.goods.model.valid;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

/**
 * 验收明细参数
 * @author lw
 *
 */
public class OrdJhBodyReq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PLUID
     * 商品ID
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "商品ID不能为空")
    private Long pluId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PLUCODE
     * 商品编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotBlank(message = "商品编码不能为空")
    private String pluCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PLUNAME
     * 商品名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String pluName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.BARCODE
     * 商品条码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.SPEC
     * 规格
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.UNIT
     * 单位
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.CARGONO
     * 货号
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String carGoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.DEPID
     * 部门Id
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.DEPCODE
     * 部门编码
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotBlank(message = "部门编码不能为空")
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.DEPNAME
     * 部门名称
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.HJPRICE
     * 含税进价
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "含税进价不能为空")
    private Double hjPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.WJPRICE
     * 无税进价
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "无税进价不能为空")
    private Double wjPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PSPRICE
     * 配送价
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "配送价不能为空")
    private Double psPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PRICE
     * 售价
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "售价不能为空")
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.JTAXRATE
     * 进项税率
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Integer jTaxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PACKUNIT
     * 包装单位
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String packUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PACKQTY
     * 包装系数
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "包装系数不能为空")
    private Double packQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PACKCOUNT
     * 包装数量
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "包装数量不能为空")
    private Double packCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.SGLCOUNT
     * 单件件数
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "单件件数不能为空")
    private Double sglCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.JHCOUNT
     * 进货数量
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "进货数量不能为空")
    private Double jhCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PSSHCOUNT
     * 配送收货数量（实际数量）默认等于进货数量
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "配送收货数量不能为空")
    private Double psShCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.HCOST
     * 含税进价金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "含税进价金额不能为空")
    private Double hCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.WCOST
     * 无税进价金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "无税进价金额不能为空")
    private Double wCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.JTAXTOTAL
     * 进项税额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "进项税额不能为空")
    private Double jTaxTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.PSCOST
     * 配送金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "配送金额不能为空")
    private Double psCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.STOTAL
     * 售价金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "售价金额不能为空")
    private Double sTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.CJTOTAL
     * 进销差价
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "进销差价不能为空")
    private Double cjTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.CJRATE
     * 进销差率
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "进销差率不能为空")
    private Double cjRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.SCDATE
     * 生产日期
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String scDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.DQDATE
     * 到期日期
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String dqDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.BZDAYS
     * 保质期
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private Integer bzDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.CXINFO
     * 赠品信息
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String cxInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.REMARK
     * 备注
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.HJSTOTAL
     * 含税结算金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "含税结算金额不能为空")
    private Double hjsTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.WJSTOTAL
     * 无税结算金额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "无税结算金额不能为空")
    private Double wjsTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.WPSPRICE
     * 无税配送价:当进价为0时不回填供应商商品分析参数表中的最新进价，
     * 不为0时需要回填供应商商品分析参数表中的最新进价信息
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "无税配送价不能为空")
    private Double wPsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.WPSCOST
     * 无税配送金额:直送验收时使用
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "无税配送金额不能为空")
    private Double wPsCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.XTAXRATE
     * 销项税率
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "销项税率不能为空")
    private Integer xTaxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TORDJHBODY.XTAXTOTAL
     * 销项税额
     * @mbggenerated Tue Jun 04 15:32:25 CST 2019
     */
    @NotNull(message = "销项税额不能为空")
    private Double xTaxTotal;

    /**
     * @return the pluId
     */
    public Long getPluId() {
        return pluId;
    }

    /**
     * @param pluId the pluId to set
     */
    public void setPluId(Long pluId) {
        this.pluId = pluId;
    }

    /**
     * @return the pluCode
     */
    public String getPluCode() {
        return pluCode;
    }

    /**
     * @param pluCode the pluCode to set
     */
    public void setPluCode(String pluCode) {
        this.pluCode = pluCode;
    }

    /**
     * @return the pluName
     */
    public String getPluName() {
        return pluName;
    }

    /**
     * @param pluName the pluName to set
     */
    public void setPluName(String pluName) {
        this.pluName = pluName;
    }

    /**
     * @return the barCode
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * @param barCode the barCode to set
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    /**
     * @return the spec
     */
    public String getSpec() {
        return spec;
    }

    /**
     * @param spec the spec to set
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * @return the unit
     */
    public String getUnit() {
        return unit;
    }

    /**
     * @param unit the unit to set
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * @return the carGoNo
     */
    public String getCarGoNo() {
        return carGoNo;
    }

    /**
     * @param carGoNo the carGoNo to set
     */
    public void setCarGoNo(String carGoNo) {
        this.carGoNo = carGoNo;
    }

    /**
     * @return the depId
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * @param depId the depId to set
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }

    /**
     * @return the depName
     */
    public String getDepName() {
        return depName;
    }

    /**
     * @param depName the depName to set
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }

    /**
     * @return the hjPrice
     */
    public Double getHjPrice() {
        return hjPrice;
    }

    /**
     * @param hjPrice the hjPrice to set
     */
    public void setHjPrice(Double hjPrice) {
        this.hjPrice = hjPrice;
    }

    /**
     * @return the wjPrice
     */
    public Double getWjPrice() {
        return wjPrice;
    }

    /**
     * @param wjPrice the wjPrice to set
     */
    public void setWjPrice(Double wjPrice) {
        this.wjPrice = wjPrice;
    }

    /**
     * @return the psPrice
     */
    public Double getPsPrice() {
        return psPrice;
    }

    /**
     * @param psPrice the psPrice to set
     */
    public void setPsPrice(Double psPrice) {
        this.psPrice = psPrice;
    }

    /**
     * @return the price
     */
    public Double getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * @return the jTaxRate
     */
    public Integer getjTaxRate() {
        return jTaxRate;
    }

    /**
     * @param jTaxRate the jTaxRate to set
     */
    public void setjTaxRate(Integer jTaxRate) {
        this.jTaxRate = jTaxRate;
    }

    /**
     * @return the packUnit
     */
    public String getPackUnit() {
        return packUnit;
    }

    /**
     * @param packUnit the packUnit to set
     */
    public void setPackUnit(String packUnit) {
        this.packUnit = packUnit;
    }

    /**
     * @return the packQty
     */
    public Double getPackQty() {
        return packQty;
    }

    /**
     * @param packQty the packQty to set
     */
    public void setPackQty(Double packQty) {
        this.packQty = packQty;
    }

    /**
     * @return the packCount
     */
    public Double getPackCount() {
        return packCount;
    }

    /**
     * @param packCount the packCount to set
     */
    public void setPackCount(Double packCount) {
        this.packCount = packCount;
    }

    /**
     * @return the sglCount
     */
    public Double getSglCount() {
        return sglCount;
    }

    /**
     * @param sglCount the sglCount to set
     */
    public void setSglCount(Double sglCount) {
        this.sglCount = sglCount;
    }

    /**
     * @return the jhCount
     */
    public Double getJhCount() {
        return jhCount;
    }

    /**
     * @param jhCount the jhCount to set
     */
    public void setJhCount(Double jhCount) {
        this.jhCount = jhCount;
    }

    /**
     * @return the psShCount
     */
    public Double getPsShCount() {
        return psShCount;
    }

    /**
     * @param psShCount the psShCount to set
     */
    public void setPsShCount(Double psShCount) {
        this.psShCount = psShCount;
    }

    /**
     * @return the hCost
     */
    public Double gethCost() {
        return hCost;
    }

    /**
     * @param hCost the hCost to set
     */
    public void sethCost(Double hCost) {
        this.hCost = hCost;
    }

    /**
     * @return the wCost
     */
    public Double getwCost() {
        return wCost;
    }

    /**
     * @param wCost the wCost to set
     */
    public void setwCost(Double wCost) {
        this.wCost = wCost;
    }

    /**
     * @return the jTaxTotal
     */
    public Double getjTaxTotal() {
        return jTaxTotal;
    }

    /**
     * @param jTaxTotal the jTaxTotal to set
     */
    public void setjTaxTotal(Double jTaxTotal) {
        this.jTaxTotal = jTaxTotal;
    }

    /**
     * @return the psCost
     */
    public Double getPsCost() {
        return psCost;
    }

    /**
     * @param psCost the psCost to set
     */
    public void setPsCost(Double psCost) {
        this.psCost = psCost;
    }

    /**
     * @return the sTotal
     */
    public Double getsTotal() {
        return sTotal;
    }

    /**
     * @param sTotal the sTotal to set
     */
    public void setsTotal(Double sTotal) {
        this.sTotal = sTotal;
    }

    /**
     * @return the cjTotal
     */
    public Double getCjTotal() {
        return cjTotal;
    }

    /**
     * @param cjTotal the cjTotal to set
     */
    public void setCjTotal(Double cjTotal) {
        this.cjTotal = cjTotal;
    }

    /**
     * @return the cjRate
     */
    public Double getCjRate() {
        return cjRate;
    }

    /**
     * @param cjRate the cjRate to set
     */
    public void setCjRate(Double cjRate) {
        this.cjRate = cjRate;
    }

    /**
     * @return the scDate
     */
    public String getScDate() {
        return scDate;
    }

    /**
     * @param scDate the scDate to set
     */
    public void setScDate(String scDate) {
        this.scDate = scDate;
    }

    /**
     * @return the dqDate
     */
    public String getDqDate() {
        return dqDate;
    }

    /**
     * @param dqDate the dqDate to set
     */
    public void setDqDate(String dqDate) {
        this.dqDate = dqDate;
    }

    /**
     * @return the bzDays
     */
    public Integer getBzDays() {
        return bzDays;
    }

    /**
     * @param bzDays the bzDays to set
     */
    public void setBzDays(Integer bzDays) {
        this.bzDays = bzDays;
    }

    /**
     * @return the cxInfo
     */
    public String getCxInfo() {
        return cxInfo;
    }

    /**
     * @param cxInfo the cxInfo to set
     */
    public void setCxInfo(String cxInfo) {
        this.cxInfo = cxInfo;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the hjsTotal
     */
    public Double getHjsTotal() {
        return hjsTotal;
    }

    /**
     * @param hjsTotal the hjsTotal to set
     */
    public void setHjsTotal(Double hjsTotal) {
        this.hjsTotal = hjsTotal;
    }

    /**
     * @return the wjsTotal
     */
    public Double getWjsTotal() {
        return wjsTotal;
    }

    /**
     * @param wjsTotal the wjsTotal to set
     */
    public void setWjsTotal(Double wjsTotal) {
        this.wjsTotal = wjsTotal;
    }

    /**
     * @return the wPsPrice
     */
    public Double getwPsPrice() {
        return wPsPrice;
    }

    /**
     * @param wPsPrice the wPsPrice to set
     */
    public void setwPsPrice(Double wPsPrice) {
        this.wPsPrice = wPsPrice;
    }

    /**
     * @return the wPsCost
     */
    public Double getwPsCost() {
        return wPsCost;
    }

    /**
     * @param wPsCost the wPsCost to set
     */
    public void setwPsCost(Double wPsCost) {
        this.wPsCost = wPsCost;
    }

    /**
     * @return the xTaxRate
     */
    public Integer getxTaxRate() {
        return xTaxRate;
    }

    /**
     * @param xTaxRate the xTaxRate to set
     */
    public void setxTaxRate(Integer xTaxRate) {
        this.xTaxRate = xTaxRate;
    }

    /**
     * @return the xTaxTotal
     */
    public Double getxTaxTotal() {
        return xTaxTotal;
    }

    /**
     * @param xTaxTotal the xTaxTotal to set
     */
    public void setxTaxTotal(Double xTaxTotal) {
        this.xTaxTotal = xTaxTotal;
    }
}
