package com.addlove.service.goods.model.valid;

import java.util.List;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

/**
 * 调拨主表参数
 * @author lw
 *
 */
public class StkDbHeadReq {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.BILLNO
     * 单据号
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String billNo;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.EMPID
     * 经手人ID
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.EMPCODE
     * 经手人编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String empCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.EMPNAME
     * 经手人姓名
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String empName;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.ORGCODE
     * 组织编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    @NotBlank(message = "组织编码不能为空")
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.ORGNAME
     * 组织名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPID
     * 部门ID
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPCODE
     * 部门编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DEPNAME
     * 部门名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String depName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.SHORGCODE
     * 调入组织编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String shOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.SHORGNAME
     * 调入组织名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String shOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.SHDEPID
     * 调入部门ID
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private Long shDepId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.SHDEPCODE
     * 调入组织编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String shDepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.SHDEPNAME
     * 调入组织名称
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String shDepName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.DBCOUNT
     * 调拨数量
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    @NotNull(message = "调拨数量不能为空")
    private Double dbCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.WCOST
     * 无税进价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    @NotNull(message = "无税进价金额不能为空")
    private Double wCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.HCOST
     * 含税进价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    @NotNull(message = "含税进价金额不能为空")
    private Double hCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.REMARK
     * 备注
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.INORGCODE
     * 内部组织编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    @NotBlank(message = "内部组织编码不能为空")
    private String inOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.INSHORGCODE
     * 调入内部组织编码
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    private String inShOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.RHCOST
     * 调出调入含税进价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    @NotNull(message = "调出调入含税进价金额不能为空")
    private Double rhCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.RWCOST
     * 调出调入无税进价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    @NotNull(message = "调出调入无税进价金额不能为空")
    private Double rwCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSTKDBHEAD.STOTAL
     * 售价金额
     * @mbggenerated Tue Jun 25 13:39:20 CST 2019
     */
    @NotNull(message = "售价金额不能为空")
    private Double sTotal;
   
    /**
    * 保存类型：1-保存；2-记账
    */
   @NotNull(message = "保存类型不能为空")
   private Integer saveType;
   
   /**
    * 商品明细
    */
   private List<StkDbBodyReq> bodyList;

    /**
     * @return the billNo
     */
    public String getBillNo() {
        return billNo;
    }
    
    /**
     * @param billNo the billNo to set
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo;
    }
    
    /**
     * @return the empId
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * @param empId the empId to set
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * @return the empCode
     */
    public String getEmpCode() {
        return empCode;
    }

    /**
     * @param empCode the empCode to set
     */
    public void setEmpCode(String empCode) {
        this.empCode = empCode;
    }

    /**
     * @return the empName
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * @param empName the empName to set
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * @return the orgCode
     */
    public String getOrgCode() {
        return orgCode;
    }
    
    /**
     * @param orgCode the orgCode to set
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }
    
    /**
     * @return the orgName
     */
    public String getOrgName() {
        return orgName;
    }
    
    /**
     * @param orgName the orgName to set
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    
    /**
     * @return the depId
     */
    public Long getDepId() {
        return depId;
    }
    
    /**
     * @param depId the depId to set
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }
    
    /**
     * @return the depCode
     */
    public String getDepCode() {
        return depCode;
    }
    
    /**
     * @param depCode the depCode to set
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode;
    }
    
    /**
     * @return the depName
     */
    public String getDepName() {
        return depName;
    }
    
    /**
     * @param depName the depName to set
     */
    public void setDepName(String depName) {
        this.depName = depName;
    }
    
    /**
     * @return the shOrgCode
     */
    public String getShOrgCode() {
        return shOrgCode;
    }
    
    /**
     * @param shOrgCode the shOrgCode to set
     */
    public void setShOrgCode(String shOrgCode) {
        this.shOrgCode = shOrgCode;
    }
    
    /**
     * @return the shOrgName
     */
    public String getShOrgName() {
        return shOrgName;
    }
    
    /**
     * @param shOrgName the shOrgName to set
     */
    public void setShOrgName(String shOrgName) {
        this.shOrgName = shOrgName;
    }
    
    /**
     * @return the shDepId
     */
    public Long getShDepId() {
        return shDepId;
    }
    
    /**
     * @param shDepId the shDepId to set
     */
    public void setShDepId(Long shDepId) {
        this.shDepId = shDepId;
    }
    
    /**
     * @return the shDepCode
     */
    public String getShDepCode() {
        return shDepCode;
    }
    
    /**
     * @param shDepCode the shDepCode to set
     */
    public void setShDepCode(String shDepCode) {
        this.shDepCode = shDepCode;
    }
    
    /**
     * @return the shDepName
     */
    public String getShDepName() {
        return shDepName;
    }
    
    /**
     * @param shDepName the shDepName to set
     */
    public void setShDepName(String shDepName) {
        this.shDepName = shDepName;
    }
    
    /**
     * @return the dbCount
     */
    public Double getDbCount() {
        return dbCount;
    }
    
    /**
     * @param dbCount the dbCount to set
     */
    public void setDbCount(Double dbCount) {
        this.dbCount = dbCount;
    }
    
    /**
     * @return the wCost
     */
    public Double getwCost() {
        return wCost;
    }
    
    /**
     * @param wCost the wCost to set
     */
    public void setwCost(Double wCost) {
        this.wCost = wCost;
    }
    
    /**
     * @return the hCost
     */
    public Double gethCost() {
        return hCost;
    }
    
    /**
     * @param hCost the hCost to set
     */
    public void sethCost(Double hCost) {
        this.hCost = hCost;
    }
    
    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }
    
    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    /**
     * @return the inOrgCode
     */
    public String getInOrgCode() {
        return inOrgCode;
    }
    
    /**
     * @param inOrgCode the inOrgCode to set
     */
    public void setInOrgCode(String inOrgCode) {
        this.inOrgCode = inOrgCode;
    }
    
    /**
     * @return the inShOrgCode
     */
    public String getInShOrgCode() {
        return inShOrgCode;
    }
    
    /**
     * @param inShOrgCode the inShOrgCode to set
     */
    public void setInShOrgCode(String inShOrgCode) {
        this.inShOrgCode = inShOrgCode;
    }
    
    /**
     * @return the rhCost
     */
    public Double getRhCost() {
        return rhCost;
    }
    
    /**
     * @param rhCost the rhCost to set
     */
    public void setRhCost(Double rhCost) {
        this.rhCost = rhCost;
    }
    
    /**
     * @return the rwCost
     */
    public Double getRwCost() {
        return rwCost;
    }
    
    /**
     * @param rwCost the rwCost to set
     */
    public void setRwCost(Double rwCost) {
        this.rwCost = rwCost;
    }
    
    /**
     * @return the sTotal
     */
    public Double getsTotal() {
        return sTotal;
    }
    
    /**
     * @param sTotal the sTotal to set
     */
    public void setsTotal(Double sTotal) {
        this.sTotal = sTotal;
    }
    
    /**
     * @return the saveType
     */
    public Integer getSaveType() {
        return saveType;
    }
    
    /**
     * @param saveType the saveType to set
     */
    public void setSaveType(Integer saveType) {
        this.saveType = saveType;
    }
    
    /**
     * @return the bodyList
     */
    public List<StkDbBodyReq> getBodyList() {
        return bodyList;
    }
    
    /**
     * @param bodyList the bodyList to set
     */
    public void setBodyList(List<StkDbBodyReq> bodyList) {
        this.bodyList = bodyList;
    }
}
